"""
tutor/intensive_english.py - the English course: 4 weeks, A2 to B1.

One aim: to make the learner's sentences grow. Half the lessons teach linking
words (and, because, although, so that...) - how to join short sentences into
long ones; the other half teach phrasal verbs - how to say it the way people
really speak. Weeks 1-2 are A2, weeks 3-4 are B1; everything is explained in
simple English, with the Azerbaijani translation on the board.

Every lesson has the same parts as the Slovak course, with one difference:
instead of translating, the learner BUILDS sentences - joins two short ones
with the lesson's linking word, or swaps a plain verb for a phrasal verb.
"""
from __future__ import annotations


def _items(rows: list[tuple]) -> list[dict]:
    return [{"text": t, "meaning": m, "native": az, "example": ex} for t, m, az, ex in rows]


def _lesson(lid: str, week: int, day: int, band: str, title: str, goal: str,
            words: list, phrases: list, grammar: dict, partner_role: str,
            dialogue: list, build: list, questions: list, speak: str,
            skills: list[str] | None = None) -> dict:
    return {
        "id": lid, "week": week, "day": day, "band": band, "title": title, "goal": goal,
        "words": _items(words),
        "phrases": [{"text": t, "meaning": m, "native": az} for t, m, az in phrases],
        "grammar": dict(grammar, skills=skills or []),
        "partner_role": partner_role,
        "dialogue": [{"who": who, "text": text, "meaning": ""} for who, text in dialogue],
        "translate": [],
        "build": [{"task": task, "answer": answer} for task, answer in build],
        "questions": [{"q": q, "meaning": "", "example": ex} for q, ex in questions],
        "speak": speak,
    }


LESSONS: list[dict] = [
    # ══ WEEK 1 - A2: joining ideas ═══════════════════════════════════════════
    _lesson(
        "en-i01", 1, 1, "A2", "and, but, or, so - joining two ideas",
        "join two short sentences into one with and, but, or, so",
        words=[
            ("and", "adds one more thing", "və", "I cook and my wife cleans."),
            ("but", "shows a difference", "amma", "It is cheap, but it is good."),
            ("or", "gives a choice", "yoxsa, və ya", "Do you want tea or coffee?"),
            ("so", "shows a result", "ona görə", "I was tired, so I went to bed."),
            ("both ... and", "the two things together", "həm ... həm də", "I speak both English and Russian."),
            ("either ... or", "one of two things", "ya ... ya da", "We can eat either pizza or pasta."),
        ],
        phrases=[
            ("I like it, but it is expensive.", "a plus and a minus in one sentence", "Xoşuma gəlir, amma bahadır."),
            ("I was hungry, so I made a sandwich.", "a reason and its result", "Ac idim, ona görə sendviç hazırladım."),
            ("Shall we walk or take a bus?", "offering a choice", "Piyada gedək, yoxsa avtobusla?"),
            ("I work in IT and I love it.", "adding a feeling to a fact", "İT-də işləyirəm və bunu sevirəm."),
            ("It was late, but I kept working.", "doing something anyway", "Gec idi, amma işləməyə davam etdim."),
        ],
        grammar={
            "name": "and / but / or / so",
            "rule": ("Put the linking word between two full sentences. Use a comma before but and so: "
                     "'It rained, so we stayed home.' and / or often need no comma."),
            "table": ["sentence + and / or + sentence", "sentence, + but / so + sentence"],
            "examples": [("I was tired, so I went to bed early.", ""),
                         ("The flat is small, but it is cheap.", ""),
                         ("We can meet today or tomorrow.", "")],
        },
        skills=["linking_words"],
        partner_role="friend",
        dialogue=[
            ("partner", "How was your day?"),
            ("learner", "It was long, but it was good."),
            ("partner", "Did you go out after work?"),
            ("learner", "No, I was tired, so I stayed home."),
            ("partner", "Tea or coffee now?"),
            ("learner", "Tea, please, and a biscuit."),
        ],
        build=[
            ("Join with 'so': I was hungry. I made a sandwich.", "I was hungry, so I made a sandwich."),
            ("Join with 'but': The hotel was old. It was very clean.", "The hotel was old, but it was very clean."),
            ("Join with 'and': I work in Bratislava. My wife works in Vienna.", "I work in Bratislava and my wife works in Vienna."),
            ("Join with 'or': Do you want to stay? Do you want to go?", "Do you want to stay or go?"),
        ],
        questions=[
            ("What do you like about your city, and what don't you like?", "I like the parks, but the traffic is bad."),
            ("What did you do last night?", "I was tired, so I stayed home and watched a film."),
        ],
        speak="Describe your day in 5 sentences. Every sentence must use and, but, or or so.",
    ),
    _lesson(
        "en-i02", 1, 2, "A2", "because and so - reasons and results",
        "give a reason with because and a result with so",
        words=[
            ("because", "gives the reason", "çünki", "I stayed home because I was ill."),
            ("because of", "because + a noun", "... görə", "The flight was late because of the snow."),
            ("so", "gives the result", "ona görə", "It was cold, so I wore a coat."),
            ("that's why", "starts a new sentence with the result", "məhz buna görə", "I love maps. That's why I travel."),
            ("the reason is", "introduces a reason", "səbəbi ...dır", "The reason is simple: I need practice."),
            ("since", "because (the reason is known)", "madam ki, çünki", "Since you are here, let's start."),
        ],
        phrases=[
            ("I'm learning English because I need it for work.", "a reason for learning", "İngiliscə öyrənirəm, çünki işim üçün lazımdır."),
            ("I missed the bus, so I was late.", "cause and result", "Avtobusu qaçırdım, ona görə gecikdim."),
            ("The shop was closed because of the holiday.", "because of + noun", "Mağaza bayram səbəbindən bağlı idi."),
            ("I don't have a car. That's why I cycle.", "result as a new sentence", "Maşınım yoxdur. Buna görə velosiped sürürəm."),
            ("Why? Because ...", "a short answer to why", "Niyə? Çünki ..."),
        ],
        grammar={
            "name": "because vs so",
            "rule": ("because + the reason: 'I stayed home because it rained.' so + the result: "
                     "'It rained, so I stayed home.' Same story, two directions. because of + a noun only."),
            "table": ["result + because + reason", "reason, + so + result", "because of + noun: because of the rain"],
            "examples": [("I stayed home because it was raining.", ""),
                         ("It was raining, so I stayed home.", ""),
                         ("The road was closed because of the accident.", "")],
        },
        skills=["linking_words"],
        partner_role="colleague",
        dialogue=[
            ("partner", "Why were you late this morning?"),
            ("learner", "I was late because I missed the bus."),
            ("partner", "Why did you miss it?"),
            ("learner", "My alarm didn't ring, so I woke up late."),
            ("partner", "Oh no. Do you have a car?"),
            ("learner", "No, I don't. That's why I take the bus."),
        ],
        build=[
            ("Join with 'because': I stayed home. I was ill.", "I stayed home because I was ill."),
            ("Now the other way, with 'so': I was ill. I stayed home.", "I was ill, so I stayed home."),
            ("Use 'because of': The flight was late. There was snow.", "The flight was late because of the snow."),
            ("Join with 'so': The shop was closed. I went home.", "The shop was closed, so I went home."),
        ],
        questions=[
            ("Why are you learning English?", "I'm learning English because I need it for my work."),
            ("What happened the last time you were late?", "I missed the bus, so I was late for work."),
        ],
        speak="Tell the tutor three things you do and WHY you do them, with because, so and that's why.",
    ),
    _lesson(
        "en-i03", 1, 3, "A2", "first, then, after that - telling a story",
        "tell a story in order with sequence words",
        words=[
            ("first", "the first step", "əvvəlcə", "First, I made coffee."),
            ("then", "the next step", "sonra", "Then I checked my emails."),
            ("after that", "the next step (after the last one)", "bundan sonra", "After that, I went to work."),
            ("next", "the step after", "növbəti, sonra", "Next, we visited the castle."),
            ("later", "some time after", "daha sonra", "Later, we had dinner."),
            ("finally", "the last step", "nəhayət, sonda", "Finally, I went to bed."),
        ],
        phrases=[
            ("First of all, ...", "to start a story or a list", "İlk öncə, ..."),
            ("Then we went to ...", "moving the story on", "Sonra ...-a getdik"),
            ("After that, it started to rain.", "the next event", "Bundan sonra yağış başladı."),
            ("In the end, we were happy.", "the result of the story", "Sonda xoşbəxt idik."),
            ("And finally, ...", "the last thing", "Və nəhayət, ..."),
        ],
        grammar={
            "name": "Sequence words",
            "rule": ("Put the sequence word at the start of the sentence, with a comma after it: "
                     "'First, ... Then ... After that, ... Finally, ...'. Use the past simple for a finished story."),
            "table": ["First, → Then → After that, → Finally,", "In the end = the result of everything"],
            "examples": [("First, I had breakfast.", ""),
                         ("Then I took the tram to work.", ""),
                         ("Finally, I got home at seven.", "")],
        },
        skills=["linking_words", "past_simple"],
        partner_role="friend",
        dialogue=[
            ("partner", "What did you do on Saturday?"),
            ("learner", "First, I slept late."),
            ("partner", "And then?"),
            ("learner", "Then I met a friend in the centre."),
            ("partner", "Nice. What did you do after that?"),
            ("learner", "After that, we had lunch, and finally we watched a film."),
        ],
        build=[
            ("Start with 'First': I made coffee.", "First, I made coffee."),
            ("Go on with 'Then': I read the news.", "Then I read the news."),
            ("Use 'After that': We went for a walk.", "After that, we went for a walk."),
            ("End with 'Finally': I went to bed.", "Finally, I went to bed."),
        ],
        questions=[
            ("What did you do yesterday morning, step by step?", "First, I got up at seven. Then I had breakfast."),
            ("How do you make your favourite dish?", "First, I cut the onions. Then I fry them."),
        ],
        speak="Tell the story of your last weekend in order: first, then, after that, later, finally.",
    ),
    _lesson(
        "en-i04", 1, 4, "A2", "when, before, after, while - time",
        "join two actions in time with when, before, after, while",
        words=[
            ("when", "at the time that", "... zaman, ...-anda", "When I got home, I cooked dinner."),
            ("before", "earlier than", "...-dan əvvəl", "I drink coffee before I go to work."),
            ("after", "later than", "...-dan sonra", "After I finish work, I go to the gym."),
            ("while", "during the same time", "... ərzində, ...-kən", "I listen to podcasts while I drive."),
            ("as soon as", "immediately when", "... kimi, ...-an kimi", "Call me as soon as you arrive."),
            ("until", "up to the time", "...-a qədər", "I waited until he came."),
        ],
        phrases=[
            ("When I was a child, I lived in Baku.", "the past, with when", "Uşaq olanda Bakıda yaşayırdım."),
            ("Before I go to bed, I read a little.", "a habit before another", "Yatmazdan əvvəl bir az oxuyuram."),
            ("After work, I usually cook.", "after + a noun", "İşdən sonra adətən yemək bişirirəm."),
            ("I hurt my hand while I was cooking.", "one action inside another", "Yemək bişirərkən əlimi zədələdim."),
            ("I'll call you as soon as I know.", "right at that moment", "Bilən kimi sənə zəng edəcəm."),
        ],
        grammar={
            "name": "Time linkers",
            "rule": ("The time part can come first (with a comma) or second (no comma): 'When I got home, "
                     "I ate.' = 'I ate when I got home.' After when / before / after / as soon as about the "
                     "future, use the present: 'when I arrive', not 'when I will arrive'."),
            "table": ["When + part, + main part", "main part + when + part",
                      "future: I'll call you when I arrive (not: will arrive)"],
            "examples": [("When I got home, I made dinner.", ""),
                         ("I always read before I go to sleep.", ""),
                         ("I'll call you as soon as I arrive.", "")],
        },
        skills=["linking_words", "present_simple"],
        partner_role="friend",
        dialogue=[
            ("partner", "What do you do after work?"),
            ("learner", "After I finish work, I go to the gym."),
            ("partner", "Do you listen to music while you train?"),
            ("learner", "Yes, I listen to podcasts while I run."),
            ("partner", "And when do you have dinner?"),
            ("learner", "When I get home, I cook something quick."),
        ],
        build=[
            ("Join with 'when': I got home. I made dinner.", "When I got home, I made dinner."),
            ("Join with 'before': I drink coffee. Then I go to work.", "I drink coffee before I go to work."),
            ("Join with 'while': I drive. I listen to music.", "I listen to music while I drive."),
            ("Join with 'as soon as': I will arrive. I will call you.", "I will call you as soon as I arrive."),
        ],
        questions=[
            ("What do you do before you go to bed?", "Before I go to bed, I read or check my phone."),
            ("What did you like when you were a child?", "When I was a child, I liked football."),
        ],
        speak="Describe your evening routine with when, before, after, while and as soon as.",
    ),
    _lesson(
        "en-i05", 1, 5, "A2", "also, too, as well, not only - adding",
        "add more information naturally",
        words=[
            ("also", "in addition (before the main verb)", "həmçinin", "I also speak Russian."),
            ("too", "in addition (at the end)", "də, həm də", "I like tea too."),
            ("as well", "in addition (at the end)", "həmçinin, də", "She works as well."),
            ("either", "too, in a negative sentence", "də (inkarda)", "I don't like it either."),
            ("not only ... but also", "two things, the second is a surprise", "təkcə ... deyil, həm də", "It's not only cheap but also good."),
            ("besides", "and one more reason", "bundan başqa", "Besides, it's near my flat."),
        ],
        phrases=[
            ("Me too.", "I agree / the same for me", "Mən də."),
            ("Me neither.", "the same for me, negative", "Mən də yox."),
            ("I also want to learn Slovak.", "also before the verb", "Mən həmçinin slovakca öyrənmək istəyirəm."),
            ("It's cheap, and it's close as well.", "adding a second plus", "Ucuzdur, həm də yaxındır."),
            ("Not only that, but ...", "adding something bigger", "Təkcə bu deyil, həm də ..."),
        ],
        grammar={
            "name": "also / too / as well / either",
            "rule": ("also goes before the main verb (but after am / is / are): 'I also work.' 'I am also tired.' "
                     "too and as well go at the end. In negative sentences use either at the end: "
                     "'I don't eat meat either.'"),
            "table": ["also + verb: I also cook", "... too / ... as well (end)", "negative: ... either (end)"],
            "examples": [("I also play the guitar.", ""),
                         ("My brother lives in Baku too.", ""),
                         ("I don't like horror films either.", "")],
        },
        skills=["linking_words", "word_order"],
        partner_role="new colleague",
        dialogue=[
            ("partner", "I love this city."),
            ("learner", "Me too. And it's quite safe as well."),
            ("partner", "I don't like the winters here."),
            ("learner", "I don't like them either. They are very dark."),
            ("partner", "Do you speak Slovak?"),
            ("learner", "A little. I also speak English and Russian."),
        ],
        build=[
            ("Add with 'also': I speak English. (Russian)", "I also speak Russian."),
            ("Add with 'too' at the end: My brother lives in Baku. (my sister)", "My sister lives in Baku too."),
            ("Negative with 'either': I don't eat meat. (fish)", "I don't eat fish either."),
            ("Use 'not only ... but also': The flat is cheap. It is big.", "The flat is not only cheap but also big."),
        ],
        questions=[
            ("Which languages do you speak?", "I speak Azerbaijani and English, and I also speak a little Slovak."),
            ("What do you like about your job?", "It's interesting, and it's well paid as well."),
        ],
        speak="Week 1 review: talk about yourself for one minute with and, but, so, because, when, then and also.",
    ),

    # ══ WEEK 2 - A2: everyday phrasal verbs ══════════════════════════════════
    _lesson(
        "en-i06", 2, 1, "A2", "My day - wake up, get up, go out",
        "describe your day with everyday phrasal verbs",
        words=[
            ("wake up", "stop sleeping", "oyanmaq", "I wake up at six."),
            ("get up", "leave your bed", "yataqdan qalxmaq", "I get up at half past six."),
            ("turn on / turn off", "start / stop a machine or light", "yandırmaq / söndürmək", "I turn on the kettle."),
            ("get dressed", "put your clothes on", "geyinmək", "I get dressed quickly."),
            ("go out", "leave home to have fun", "çölə çıxmaq, gəzməyə getmək", "We go out on Fridays."),
            ("come back", "return", "qayıtmaq", "I come back home at six."),
            ("stay in", "stay at home", "evdə qalmaq", "I stay in on Sundays."),
        ],
        phrases=[
            ("I wake up at six, but I get up at half past.", "two different moments", "Altıda oyanıram, amma yarımda qalxıram."),
            ("Can you turn off the light?", "a polite request", "İşığı söndürə bilərsən?"),
            ("Let's go out tonight.", "an invitation", "Gəl bu axşam çölə çıxaq."),
            ("I'd rather stay in.", "saying no to going out", "Evdə qalmağı üstün tuturam."),
            ("What time do you come back?", "asking about return", "Saat neçədə qayıdırsan?"),
        ],
        grammar={
            "name": "Phrasal verbs: verb + little word",
            "rule": ("A phrasal verb is a verb + a small word (up, out, on, off, back). Together they have a new "
                     "meaning: get = receive, get up = leave your bed. The small word is important - do not drop it."),
            "table": ["wake + up = stop sleeping", "go + out = leave home for fun", "come + back = return"],
            "examples": [("I usually get up at seven.", ""),
                         ("Please turn off your phone.", ""),
                         ("We went out for dinner last night.", "")],
        },
        skills=["phrasal_verbs"],
        partner_role="friend",
        dialogue=[
            ("partner", "What time do you wake up?"),
            ("learner", "I wake up at six, but I get up at half past six."),
            ("partner", "Do you go out in the evenings?"),
            ("learner", "Sometimes. On Fridays we go out for dinner."),
            ("partner", "And at the weekend?"),
            ("learner", "I usually stay in and relax."),
        ],
        build=[
            ("Say it with a phrasal verb: I leave my bed at seven.", "I get up at seven."),
            ("Say it with a phrasal verb: I return home at six.", "I come back home at six."),
            ("Say it with a phrasal verb: Please stop the TV.", "Please turn off the TV."),
            ("Say it with a phrasal verb: We stay at home tonight.", "We stay in tonight."),
        ],
        questions=[
            ("What time do you wake up and get up?", "I wake up at six and get up at half past six."),
            ("Do you go out or stay in at the weekend?", "I usually go out on Saturday and stay in on Sunday."),
        ],
        speak="Describe your whole day with at least six phrasal verbs from the lesson.",
    ),
    _lesson(
        "en-i07", 2, 2, "A2", "At home - clean up, put away, throw away",
        "talk about housework with phrasal verbs",
        words=[
            ("clean up", "make a place clean", "təmizləmək, yığışdırmaq", "Let's clean up the kitchen."),
            ("tidy up", "put things in order", "səliqəyə salmaq", "I tidy up my room on Sundays."),
            ("put away", "put back in its place", "yerinə qoymaq", "Put away your clothes."),
            ("throw away", "put in the bin", "atmaq (zibilə)", "I threw away the old shoes."),
            ("pick up", "take from the floor", "yerdən götürmək", "Can you pick up that paper?"),
            ("wash up", "wash the dishes", "qab yumaq", "I cook and he washes up."),
            ("take out", "carry outside", "çıxarmaq", "Please take out the rubbish."),
        ],
        phrases=[
            ("Whose turn is it to wash up?", "sharing chores", "Qab yumaq kimin növbəsidir?"),
            ("Can you take out the rubbish?", "a request", "Zibili çıxara bilərsən?"),
            ("Put it away, please.", "the object in the middle", "Onu yerinə qoy, zəhmət olmasa."),
            ("Don't throw it away!", "stopping someone", "Onu atma!"),
            ("Let's tidy up before the guests come.", "a plan with before", "Qonaqlar gəlməmiş səliqəyə salaq."),
        ],
        grammar={
            "name": "Separable phrasal verbs: put it away",
            "rule": ("Many phrasal verbs can split: 'put away the dishes' or 'put the dishes away'. But with "
                     "it / them / him / her the small word MUST go at the end: 'put it away', never 'put away it'."),
            "table": ["put away the cups = put the cups away", "it / them: put it away (not: put away it)"],
            "examples": [("Please put your toys away.", ""),
                         ("That milk is old. Throw it away.", ""),
                         ("Can you pick them up?", "")],
        },
        skills=["phrasal_verbs", "word_order"],
        partner_role="flatmate",
        dialogue=[
            ("partner", "The kitchen is a mess!"),
            ("learner", "I know. Let's clean it up together."),
            ("partner", "OK. I'll wash up."),
            ("learner", "Great. I'll put the food away and take out the rubbish."),
            ("partner", "What about these old boxes?"),
            ("learner", "We don't need them. Let's throw them away."),
        ],
        build=[
            ("Use 'it': Put away the book.", "Put it away."),
            ("Use 'them': Throw away the old shoes.", "Throw them away."),
            ("Say it with a phrasal verb: Please carry the rubbish outside.", "Please take out the rubbish."),
            ("Join with 'before': We clean up. The guests come.", "We clean up before the guests come."),
        ],
        questions=[
            ("Who does the housework in your home?", "I cook and my wife washes up, and we both tidy up."),
            ("What did you throw away last time?", "I threw away some old clothes."),
        ],
        speak="Plan a cleaning day with a flatmate: who does what, using the phrasal verbs and 'it / them'.",
    ),
    _lesson(
        "en-i08", 2, 3, "A2", "People - get on with, look after, grow up",
        "talk about family and friends with phrasal verbs",
        words=[
            ("grow up", "become an adult", "böyümək", "I grew up in Baku."),
            ("get on with", "have a good relationship with", "yola getmək", "I get on well with my brother."),
            ("look after", "take care of", "qayğısına qalmaq", "She looks after her mother."),
            ("look like", "have the same face as", "oxşamaq", "I look like my father."),
            ("take after", "be similar to an older family member", "... -a çəkmək", "He takes after his mum."),
            ("find out", "discover information", "öyrənmək, bilmək", "I found out the truth."),
            ("call back", "phone again later", "geri zəng etmək", "I'll call you back."),
        ],
        phrases=[
            ("Where did you grow up?", "asking about childhood", "Harada böyümüsən?"),
            ("We get on really well.", "a good relationship", "Çox yaxşı yola gedirik."),
            ("Who looks after the kids?", "childcare", "Uşaqlara kim baxır?"),
            ("You look like your sister!", "same face", "Bacına oxşayırsan!"),
            ("Can I call you back later?", "busy on the phone", "Sonra sənə zəng edə bilərəm?"),
        ],
        grammar={
            "name": "Phrasal verbs that do not split",
            "rule": ("Some phrasal verbs never split: look after, get on with, look like. The object always "
                     "comes after them: 'look after her', not 'look her after'. Learn them as one block."),
            "table": ["look after + person: look after my son", "get on with + person", "never split: look after him"],
            "examples": [("My mum looks after my son on Mondays.", ""),
                         ("I get on well with my colleagues.", ""),
                         ("I grew up in a small town.", "")],
        },
        skills=["phrasal_verbs"],
        partner_role="friend",
        dialogue=[
            ("partner", "Where did you grow up?"),
            ("learner", "I grew up in Baku, near the sea."),
            ("partner", "Do you get on with your brother?"),
            ("learner", "Yes, we get on really well. He looks like me too."),
            ("partner", "Who looks after your parents now?"),
            ("learner", "My sister does, because she lives near them."),
        ],
        build=[
            ("Say it with a phrasal verb: I became an adult in Baku.", "I grew up in Baku."),
            ("Say it with a phrasal verb: She takes care of her grandmother.", "She looks after her grandmother."),
            ("Say it with a phrasal verb: I have a good relationship with my boss.", "I get on well with my boss."),
            ("Join with 'because': I'll call you back. I'm busy now.", "I'll call you back because I'm busy now."),
        ],
        questions=[
            ("Where did you grow up, and what was it like?", "I grew up in Baku, and it was a great place for children."),
            ("Who do you get on with best in your family?", "I get on best with my sister because she is funny."),
        ],
        speak="Talk about your family: where you grew up, who you look like, who you get on with and why.",
    ),
    _lesson(
        "en-i09", 2, 4, "A2", "Plans - look forward to, put off, carry on",
        "talk about plans and changes with phrasal verbs",
        words=[
            ("look forward to", "feel happy about something coming", "səbirsizliklə gözləmək", "I'm looking forward to the holiday."),
            ("put off", "move to a later time", "təxirə salmaq", "We put off the meeting."),
            ("call off", "cancel", "ləğv etmək", "They called off the match."),
            ("carry on", "continue", "davam etmək", "Carry on, I'm listening."),
            ("set off", "start a journey", "yola düşmək", "We set off at six."),
            ("sort out", "fix a problem or organise", "həll etmək, qaydaya salmaq", "I need to sort out my papers."),
            ("turn up", "arrive, often unexpectedly", "gəlib çıxmaq", "He turned up late."),
        ],
        phrases=[
            ("I'm looking forward to seeing you.", "to + -ing", "Səni görməyi səbirsizliklə gözləyirəm."),
            ("Let's not put it off again.", "stop delaying", "Gəl bunu yenə təxirə salmayaq."),
            ("The trip was called off.", "cancelled", "Səfər ləğv olundu."),
            ("We'll set off early.", "start the journey", "Tezdən yola düşəcəyik."),
            ("Don't worry, I'll sort it out.", "I will fix it", "Narahat olma, həll edəcəm."),
        ],
        grammar={
            "name": "look forward to + -ing",
            "rule": ("After look forward to, use a noun or verb + -ing: 'I'm looking forward to the trip', "
                     "'I'm looking forward to seeing you' - never 'to see'. Many plans use be going to or will."),
            "table": ["look forward to + noun: the weekend", "look forward to + -ing: meeting you"],
            "examples": [("I'm looking forward to the weekend.", ""),
                         ("We're going to set off at seven.", ""),
                         ("I'll sort out the tickets tomorrow.", "")],
        },
        skills=["phrasal_verbs", "future_forms"],
        partner_role="friend",
        dialogue=[
            ("partner", "Are we still going to the mountains on Saturday?"),
            ("learner", "Yes! I'm really looking forward to it."),
            ("partner", "What time shall we set off?"),
            ("learner", "Let's set off at seven, before the traffic."),
            ("partner", "And if it rains?"),
            ("learner", "Then we'll put it off until Sunday."),
        ],
        build=[
            ("Say it with a phrasal verb: We moved the meeting to next week.", "We put off the meeting until next week."),
            ("Say it with a phrasal verb: They cancelled the concert.", "They called off the concert."),
            ("Finish it: I'm looking forward to ... (see you)", "I'm looking forward to seeing you."),
            ("Join with 'so': It was snowing. We put off the trip.", "It was snowing, so we put off the trip."),
        ],
        questions=[
            ("What are you looking forward to this month?", "I'm looking forward to my holiday in Baku."),
            ("What do you often put off?", "I often put off going to the dentist."),
        ],
        speak="Plan a weekend trip: when you set off, what you look forward to, and what you do if it is called off.",
    ),
    _lesson(
        "en-i10", 2, 5, "A2", "A2 checkpoint - my story",
        "tell a longer story with linking words and phrasal verbs together",
        words=[
            ("to be honest", "saying what you really think", "düzünü desəm", "To be honest, I was nervous."),
            ("at first", "in the beginning", "əvvəlcə, ilk vaxtlar", "At first, I didn't like it."),
            ("in the end", "finally, after everything", "sonda", "In the end, it was fine."),
            ("anyway", "back to the main story", "hər halda, nəysə", "Anyway, we got there."),
            ("end up", "be in a place or situation at last", "axırda ... olmaq", "We ended up in a small café."),
            ("work out", "have a good result", "alınmaq, düzəlmək", "Everything worked out."),
        ],
        phrases=[
            ("At first, I didn't like it, but in the end I loved it.", "a change in a story", "Əvvəlcə xoşlamadım, amma sonda sevdim."),
            ("To be honest, I was a bit scared.", "an honest feeling", "Düzünü desəm, bir az qorxdum."),
            ("Anyway, where was I?", "coming back to the story", "Nəysə, harada qaldım?"),
            ("We ended up staying all night.", "end up + -ing", "Axırda bütün gecə qaldıq."),
            ("It all worked out in the end.", "a happy ending", "Sonda hər şey düzəldi."),
        ],
        grammar={
            "name": "A story with all of it",
            "rule": ("A good story: at first → then / after that → but / so / because → in the end. Use the past "
                     "simple, and a phrasal verb where people would: 'we set off', 'it worked out'."),
            "table": ["At first, ... but ...", "then / after that / so / because", "In the end, ... worked out"],
            "examples": [("At first, I didn't understand anything.", ""),
                         ("We set off early, but the car broke down.", ""),
                         ("In the end, everything worked out.", "")],
        },
        skills=["linking_words", "phrasal_verbs", "past_simple"],
        partner_role="friend",
        dialogue=[
            ("partner", "How was your first week in Bratislava?"),
            ("learner", "At first, it was hard, because I didn't know anyone."),
            ("partner", "And then?"),
            ("learner", "Then I found out about a language café, so I went there."),
            ("partner", "Did you like it?"),
            ("learner", "To be honest, I was nervous, but in the end it worked out."),
        ],
        build=[
            ("Join with 'At first ... but': I didn't like my job. Now I love it.", "At first, I didn't like my job, but now I love it."),
            ("Say it with a phrasal verb: Everything had a good result.", "Everything worked out."),
            ("Use 'end up': We finally stayed in a small café.", "We ended up in a small café."),
            ("Join with 'because' and 'so': I didn't know anyone. I was new. I joined a club.", "I didn't know anyone because I was new, so I joined a club."),
        ],
        questions=[
            ("Tell me about your first day at your job.", "At first, I was nervous, but my colleagues helped me, so in the end it was fine."),
            ("What went wrong on a trip, and how did it end?", "The car broke down, but in the end everything worked out."),
        ],
        speak="A2 checkpoint: tell a 2-minute story (a trip, a first day, a problem). Use at first, then, so, because, but, in the end and 3 phrasal verbs.",
    ),

    # ══ WEEK 3 - B1: longer sentences ════════════════════════════════════════
    _lesson(
        "en-i11", 3, 1, "B1", "although, even though, however - contrast",
        "show a contrast in one sentence or between two",
        words=[
            ("although", "shows a surprising contrast", "baxmayaraq ki", "Although it was late, I kept working."),
            ("even though", "a stronger although", "hətta ... olsa da", "Even though I was tired, I went out."),
            ("however", "but (new sentence, formal)", "lakin, bununla belə", "The job is hard. However, I like it."),
            ("despite", "although + a noun or -ing", "... -a baxmayaraq", "Despite the rain, we went out."),
            ("on the other hand", "the second side of an idea", "digər tərəfdən", "On the other hand, it's cheap."),
            ("while", "compares two different things", "halbuki, ... -sa da", "I like tea, while my wife likes coffee."),
        ],
        phrases=[
            ("Although it's expensive, it's worth it.", "a minus that doesn't matter", "Bahalı olsa da, dəyər."),
            ("Even though I was ill, I went to work.", "surprising action", "Xəstə olsam da, işə getdim."),
            ("However, there is one problem.", "a new, opposite point", "Lakin bir problem var."),
            ("Despite being tired, she finished it.", "despite + -ing", "Yorğun olmasına baxmayaraq, onu bitirdi."),
            ("On one hand ..., on the other hand ...", "two sides", "Bir tərəfdən ..., digər tərəfdən ..."),
        ],
        grammar={
            "name": "although vs however vs despite",
            "rule": ("although / even though + a full sentence: 'Although it rained, we went.' however starts a new "
                     "sentence, with a comma: 'It rained. However, we went.' despite + a noun or -ing: "
                     "'Despite the rain' - never 'despite it rained'."),
            "table": ["Although + sentence, + sentence", "Sentence. However, + sentence",
                      "Despite + noun / -ing, + sentence"],
            "examples": [("Although it was raining, we went for a walk.", ""),
                         ("The hotel was old. However, it was very clean.", ""),
                         ("Despite the traffic, we arrived on time.", "")],
        },
        skills=["linking_words"],
        partner_role="colleague",
        dialogue=[
            ("partner", "Do you like living here?"),
            ("learner", "Yes. Although the winters are dark, the city is beautiful."),
            ("partner", "And your new job?"),
            ("learner", "It's stressful. However, I'm learning a lot."),
            ("partner", "Do you still go to the gym?"),
            ("learner", "Yes, even though I'm busy, I go twice a week."),
        ],
        build=[
            ("Join with 'although': It was late. I kept working.", "Although it was late, I kept working."),
            ("Join with 'however': The flat is small. It's in the centre.", "The flat is small. However, it's in the centre."),
            ("Use 'despite': It was raining, but we went out. (the rain)", "Despite the rain, we went out."),
            ("Join with 'even though': I was tired. I went to the party.", "Even though I was tired, I went to the party."),
        ],
        questions=[
            ("What is good and bad about your city?", "Although it's small, it has everything I need."),
            ("Tell me about something you did even though it was hard.", "Even though I was scared, I moved abroad."),
        ],
        speak="Give both sides of three things (your job, your city, learning languages) with although, however and despite.",
    ),
    _lesson(
        "en-i12", 3, 2, "B1", "if, unless, as long as - conditions",
        "talk about conditions and possible results",
        words=[
            ("if", "on the condition that", "əgər", "If it rains, we'll stay in."),
            ("unless", "if not", "... -sa, yoxsa; əgər ... -masa", "I'll go unless it rains."),
            ("as long as", "only on this condition", "... şərtilə, ... -dıqca", "You can stay as long as you're quiet."),
            ("in case", "to be ready if it happens", "hər ehtimala qarşı", "Take an umbrella in case it rains."),
            ("otherwise", "if not, then", "əks halda", "Hurry, otherwise we'll be late."),
            ("what if", "imagine this happens", "bəs əgər", "What if we miss the train?"),
        ],
        phrases=[
            ("If I have time, I'll call you.", "a real future condition", "Vaxtım olsa, sənə zəng edəcəm."),
            ("I won't go unless you come too.", "only if you come", "Sən də gəlməsən, getmərəm."),
            ("It's fine, as long as you're happy.", "one condition", "Sən xoşbəxt olduqca, hər şey qaydasındadır."),
            ("Take a jacket in case it gets cold.", "being ready", "Hər ehtimala qarşı gödəkçə götür."),
            ("What if it doesn't work?", "a worry", "Bəs əgər alınmasa?"),
        ],
        grammar={
            "name": "First conditional: if + present, will",
            "rule": ("For a real future: if + present, will + verb: 'If it rains, we'll stay in.' Not 'if it will "
                     "rain'. unless = if not: 'unless it rains' = 'if it doesn't rain'."),
            "table": ["If + present, will + verb", "unless = if not", "in case = to be ready if"],
            "examples": [("If I finish early, I'll go to the gym.", ""),
                         ("We'll miss the bus unless we leave now.", ""),
                         ("I'll take some cash in case the card doesn't work.", "")],
        },
        skills=["linking_words", "first_conditional"],
        partner_role="friend",
        dialogue=[
            ("partner", "Shall we have a picnic tomorrow?"),
            ("learner", "Sure, if the weather is good."),
            ("partner", "And if it rains?"),
            ("learner", "Then we'll go to the cinema instead."),
            ("partner", "Should I bring anything?"),
            ("learner", "Bring a blanket in case the grass is wet."),
        ],
        build=[
            ("Join with 'if': It rains tomorrow. We will stay in.", "If it rains tomorrow, we will stay in."),
            ("Say it with 'unless': I will go if it doesn't rain.", "I will go unless it rains."),
            ("Join with 'in case': Take an umbrella. It might rain.", "Take an umbrella in case it rains."),
            ("Join with 'otherwise': Leave now. We will be late.", "Leave now, otherwise we will be late."),
        ],
        questions=[
            ("What will you do if you have a free day this week?", "If I have a free day, I'll go to the mountains."),
            ("What do you always take with you, in case?", "I always take a charger in case my phone dies."),
        ],
        speak="Plan a trip with conditions: if the weather is bad, unless the train is late, in case something goes wrong.",
    ),
    _lesson(
        "en-i13", 3, 3, "B1", "so that, in order to, to - purpose",
        "say why you do something (the purpose)",
        words=[
            ("to", "for this purpose (+ verb)", "... üçün", "I went out to buy bread."),
            ("in order to", "a more formal 'to'", "... məqsədilə", "I study in order to get a better job."),
            ("so that", "purpose + a full sentence", "... ki, ... deyə", "I spoke slowly so that he understood."),
            ("for", "purpose + a noun", "... üçün", "I went to the shop for some milk."),
            ("so as not to", "purpose, negative", "... -mamaq üçün", "I left early so as not to be late."),
            ("the point is", "the main purpose", "məsələ ondadır ki", "The point is to practise every day."),
        ],
        phrases=[
            ("I'm learning English to get a better job.", "purpose with to", "Daha yaxşı iş tapmaq üçün ingiliscə öyrənirəm."),
            ("I set an alarm so that I don't oversleep.", "so that + sentence", "Yuxuda qalmayım deyə zəngli saat qururam."),
            ("She called to say sorry.", "short purpose", "Üzr istəmək üçün zəng etdi."),
            ("I went to the pharmacy for some medicine.", "for + noun", "Dərman üçün aptekə getdim."),
            ("I whispered so as not to wake the baby.", "negative purpose", "Körpəni oyatmamaq üçün pıçıldadım."),
        ],
        grammar={
            "name": "to / so that / for",
            "rule": ("to + verb: 'I came to help.' (never 'for help you'). for + noun: 'I came for the meeting.' "
                     "so that + a full sentence, often with can / could / will: 'I left early so that I could park.'"),
            "table": ["to + verb: to learn", "for + noun: for a coffee", "so that + sentence: so that I can ..."],
            "examples": [("I moved to Slovakia to work.", ""),
                         ("I'm saving money so that I can buy a car.", ""),
                         ("We stopped for a coffee.", "")],
        },
        skills=["linking_words", "verb_patterns"],
        partner_role="colleague",
        dialogue=[
            ("partner", "Why are you taking English classes?"),
            ("learner", "I'm taking them to get better at meetings."),
            ("partner", "Do you practise at home too?"),
            ("learner", "Yes, I watch films in English so that I can hear real speech."),
            ("partner", "Smart. Why did you come in early today?"),
            ("learner", "I came early to finish the report."),
        ],
        build=[
            ("Join with 'to': I went out. I wanted to buy bread.", "I went out to buy bread."),
            ("Join with 'so that': I spoke slowly. He could understand me.", "I spoke slowly so that he could understand me."),
            ("Correct it: I came here for help you.", "I came here to help you."),
            ("Use 'for': I went to the café. I wanted a coffee.", "I went to the café for a coffee."),
        ],
        questions=[
            ("Why did you come to Slovakia?", "I came to Slovakia to work in IT."),
            ("What do you do so that you remember new words?", "I write them down so that I can review them."),
        ],
        speak="Explain the purpose of five things you do (work, study, save money, sport, travel) with to, so that and for.",
    ),
    _lesson(
        "en-i14", 3, 4, "B1", "who, which, where - adding detail",
        "add detail to a sentence with who, which, where",
        words=[
            ("who", "for people", "hansı ki (insan)", "I have a friend who lives in Paris."),
            ("which", "for things", "hansı ki (əşya)", "I bought a car which is very old."),
            ("that", "for people or things (informal)", "hansı ki", "The film that we saw was great."),
            ("where", "for places", "harada ki", "This is the café where we met."),
            ("whose", "for owners", "kimin ki", "I know a man whose son is a pilot."),
            ("when", "for times", "o zaman ki", "I remember the day when we met."),
        ],
        phrases=[
            ("She's the colleague who helped me.", "describing a person", "Mənə kömək edən həmkar odur."),
            ("It's a phone which takes great photos.", "describing a thing", "Əla şəkil çəkən telefondur."),
            ("That's the place where I grew up.", "describing a place", "Böyüdüyüm yer oradır."),
            ("The book that you gave me is great.", "that for things", "Mənə verdiyin kitab əladır."),
            ("I met a man whose wife is from Baku.", "whose = his / her", "Həyat yoldaşı bakılı olan bir kişi ilə tanış oldum."),
        ],
        grammar={
            "name": "Relative clauses",
            "rule": ("Join two sentences about the same thing: 'I have a friend. He lives in Paris.' → 'I have a "
                     "friend who lives in Paris.' who = people, which = things, where = places. Don't repeat "
                     "he / it: not 'who he lives'."),
            "table": ["person → who", "thing → which / that", "place → where", "don't repeat: who (he) lives"],
            "examples": [("I have a colleague who speaks five languages.", ""),
                         ("This is the app which I use every day.", ""),
                         ("Baku is the city where I was born.", "")],
        },
        skills=["relative_clauses"],
        partner_role="friend",
        dialogue=[
            ("partner", "Who is that man in the photo?"),
            ("learner", "He's the teacher who taught me English."),
            ("partner", "And where was this?"),
            ("learner", "That's the school where I studied in Baku."),
            ("partner", "Is that your car?"),
            ("learner", "Yes, it's the car which I bought last year."),
        ],
        build=[
            ("Join with 'who': I have a friend. He lives in Paris.", "I have a friend who lives in Paris."),
            ("Join with 'which': I bought a phone. It takes great photos.", "I bought a phone which takes great photos."),
            ("Join with 'where': This is the café. We met there.", "This is the café where we met."),
            ("Join with 'whose': I know a woman. Her son is a pilot.", "I know a woman whose son is a pilot."),
        ],
        questions=[
            ("Describe a person who is important to you.", "My sister is a person who always helps me."),
            ("Tell me about a place where you feel happy.", "The sea in Baku is a place where I feel happy."),
        ],
        speak="Describe your city, your best friend and your favourite app - each with who, which or where.",
    ),
    _lesson(
        "en-i15", 3, 5, "B1", "as a result, therefore, that's why - consequences",
        "explain causes and consequences clearly",
        words=[
            ("as a result", "this is the result", "nəticədə", "It snowed. As a result, the schools closed."),
            ("therefore", "so (formal)", "buna görə də", "He was ill. Therefore, he stayed home."),
            ("that's why", "so (spoken)", "məhz buna görə", "I love it. That's why I do it."),
            ("due to", "because of (formal)", "... səbəbindən", "The train is late due to the weather."),
            ("thanks to", "because of (a good thing)", "... sayəsində", "Thanks to you, I passed."),
            ("this means", "this has the result", "bu o deməkdir ki", "Prices went up. This means we pay more."),
        ],
        phrases=[
            ("As a result, I had to wait two hours.", "a bad consequence", "Nəticədə iki saat gözləməli oldum."),
            ("Thanks to her help, I found a flat.", "a good cause", "Onun köməyi sayəsində mənzil tapdım."),
            ("The flight was cancelled due to fog.", "an official reason", "Reys duman səbəbindən ləğv edildi."),
            ("That's why I always check the weather.", "a lesson learned", "Buna görə həmişə havaya baxıram."),
            ("This means we need a new plan.", "the next step", "Bu o deməkdir ki, yeni plan lazımdır."),
        ],
        grammar={
            "name": "Linking two sentences: cause → result",
            "rule": ("as a result, therefore and this means start a NEW sentence and have a comma after them "
                     "(except 'this means'). due to / thanks to + a noun: 'thanks to your help' - thanks to "
                     "is only for good results."),
            "table": ["Cause. As a result, / Therefore, result.", "due to / thanks to + noun",
                      "thanks to = good result only"],
            "examples": [("It was snowing. As a result, the road was closed.", ""),
                         ("Thanks to my friend, I got the job.", ""),
                         ("The meeting was cancelled due to the strike.", "")],
        },
        skills=["linking_words", "discourse_markers"],
        partner_role="colleague",
        dialogue=[
            ("partner", "Why is the project late?"),
            ("learner", "Two people were ill. As a result, we lost a week."),
            ("partner", "Can we still finish on time?"),
            ("learner", "Thanks to the new tools, I think we can."),
            ("partner", "So what's the plan?"),
            ("learner", "We start earlier every day. That's why I'm here at eight."),
        ],
        build=[
            ("Join with 'As a result': It snowed a lot. The schools closed.", "It snowed a lot. As a result, the schools closed."),
            ("Use 'thanks to': My friend helped me. I found a flat.", "Thanks to my friend, I found a flat."),
            ("Use 'due to': The train is late. The weather is bad.", "The train is late due to the bad weather."),
            ("Join with 'That's why': I love languages. I study every day.", "I love languages. That's why I study every day."),
        ],
        questions=[
            ("What changed in your life when you moved, and what was the result?", "I moved to Bratislava. As a result, I started learning Slovak."),
            ("Who helped you a lot, and what happened thanks to them?", "Thanks to my brother, I found my first job."),
        ],
        speak="Tell two stories of cause and result - one good (thanks to), one bad (as a result, due to).",
    ),

    # ══ WEEK 4 - B1: phrasal verbs for fluent talk ═══════════════════════════
    _lesson(
        "en-i16", 4, 1, "B1", "Work - take on, deal with, figure out",
        "talk about work with B1 phrasal verbs",
        words=[
            ("take on", "accept work or responsibility", "öhdəsinə götürmək", "I took on a new project."),
            ("deal with", "handle a problem or person", "məşğul olmaq, öhdəsindən gəlmək", "I deal with clients every day."),
            ("figure out", "understand after thinking", "anlamaq, başa düşmək", "I can't figure out this bug."),
            ("set up", "start or prepare", "qurmaq, təşkil etmək", "We set up a new company."),
            ("run out of", "have none left", "... tükənmək", "We ran out of time."),
            ("catch up", "reach the same level / talk about news", "çatmaq, xəbərləşmək", "I need to catch up on emails."),
            ("hand in", "give work to someone", "təhvil vermək", "Hand in the report by Friday."),
        ],
        phrases=[
            ("I'll deal with it.", "taking responsibility", "Mən bununla məşğul olaram."),
            ("We're running out of time.", "a deadline is close", "Vaxtımız tükənir."),
            ("Let me figure it out.", "I will find the answer", "Qoy özüm anlayım."),
            ("Can we catch up tomorrow?", "a short meeting", "Sabah danışa bilərik?"),
            ("I've taken on too much.", "too much work", "Özümə çox iş götürmüşəm."),
        ],
        grammar={
            "name": "Three-word phrasal verbs",
            "rule": ("Some phrasal verbs have three words: run out of, catch up on, get on with. The object comes "
                     "after all three: 'we ran out of milk'. The -ing form after a preposition: 'I'm dealing with it'."),
            "table": ["run out of + thing: run out of time", "catch up on + thing: catch up on emails",
                      "separable: figure it out · set it up"],
            "examples": [("I dealt with three angry clients today.", ""),
                         ("We ran out of coffee at the office.", ""),
                         ("It took me an hour to figure it out.", "")],
        },
        skills=["phrasal_verbs"],
        partner_role="manager",
        dialogue=[
            ("partner", "Can you take on the new client?"),
            ("learner", "I'd like to, but I've got a lot on right now."),
            ("partner", "What's the problem?"),
            ("learner", "I'm still dealing with the bug from last week."),
            ("partner", "Have you figured it out?"),
            ("learner", "Almost. If I sort it out today, I can take on the client tomorrow."),
        ],
        build=[
            ("Say it with a phrasal verb: We have no more time.", "We have run out of time."),
            ("Say it with a phrasal verb: I handle clients every day.", "I deal with clients every day."),
            ("Say it with a phrasal verb and 'it': I can't understand this problem.", "I can't figure it out."),
            ("Join with 'although': I took on the project. I was very busy.", "Although I was very busy, I took on the project."),
        ],
        questions=[
            ("What problems do you deal with at work?", "I deal with bugs and sometimes with difficult clients."),
            ("When did you last run out of time, and what happened?", "Last week we ran out of time, so we worked late."),
        ],
        speak="Describe a busy week at work: what you took on, what you dealt with, what you figured out.",
    ),
    _lesson(
        "en-i17", 4, 2, "B1", "Problems - break down, give up, come up with",
        "talk about problems and solutions with phrasal verbs",
        words=[
            ("break down", "stop working (a machine)", "xarab olmaq", "My car broke down on the motorway."),
            ("give up", "stop trying", "əl çəkmək, təslim olmaq", "Don't give up!"),
            ("come up with", "think of an idea", "fikir tapmaq", "She came up with a great plan."),
            ("turn down", "say no to an offer", "rədd etmək", "I turned down the job."),
            ("end up", "finally be in a situation", "axırda ... olmaq", "We ended up walking home."),
            ("work out", "find a solution / have a good end", "həll etmək, alınmaq", "We'll work it out."),
            ("put up with", "accept something bad", "dözmək", "I can't put up with the noise."),
        ],
        phrases=[
            ("The car broke down, so we ended up taking a taxi.", "a problem and its end", "Maşın xarab oldu, axırda taksiyə mindik."),
            ("Don't give up now!", "encouragement", "İndi təslim olma!"),
            ("We need to come up with a plan B.", "a new idea", "B planı tapmalıyıq."),
            ("I turned it down because the pay was low.", "saying no, with a reason", "Maaş az olduğu üçün rədd etdim."),
            ("I can't put up with it any more.", "at the limit", "Artıq buna dözə bilmirəm."),
        ],
        grammar={
            "name": "Phrasal verbs in the past",
            "rule": ("Only the verb changes, never the small word: break down → broke down, give up → gave up, "
                     "come up with → came up with. Keep the small word: 'it broke', not 'it broke down' is a "
                     "different meaning."),
            "table": ["break down → broke down", "give up → gave up", "come up with → came up with",
                      "turn down → turned down"],
            "examples": [("My laptop broke down during the meeting.", ""),
                         ("He never gave up.", ""),
                         ("We came up with a better idea.", "")],
        },
        skills=["phrasal_verbs", "past_simple"],
        partner_role="friend",
        dialogue=[
            ("partner", "How was the trip to Vienna?"),
            ("learner", "A disaster at first. The car broke down on the way."),
            ("partner", "Oh no! What did you do?"),
            ("learner", "We didn't give up. We came up with a plan and took the train."),
            ("partner", "So you got there in the end?"),
            ("learner", "Yes, we ended up arriving late, but it worked out."),
        ],
        build=[
            ("Say it with a phrasal verb: My car stopped working.", "My car broke down."),
            ("Say it with a phrasal verb: I said no to the offer.", "I turned down the offer."),
            ("Say it with a phrasal verb: She thought of a new idea.", "She came up with a new idea."),
            ("Join with 'so' and 'end up': The bus didn't come. We walked home.", "The bus didn't come, so we ended up walking home."),
        ],
        questions=[
            ("Tell me about a time something broke down.", "My laptop broke down before a meeting, so I ended up using my phone."),
            ("Have you ever turned down an offer? Why?", "Yes, I turned down a job because it was too far."),
        ],
        speak="Tell a story of a problem: what broke down, what you came up with, whether you gave up, how you ended up.",
    ),
    _lesson(
        "en-i18", 4, 3, "B1", "Feelings - fall out, make up, cheer up",
        "talk about relationships and feelings with phrasal verbs",
        words=[
            ("fall out (with)", "stop being friends after an argument", "küsmək, aranı vurmaq", "I fell out with my neighbour."),
            ("make up", "become friends again", "barışmaq", "They argued but made up quickly."),
            ("cheer up", "become happier / make happier", "kefi açılmaq, ürək-dirək vermək", "Cheer up! It's not so bad."),
            ("calm down", "become less angry or nervous", "sakitləşmək", "Calm down and tell me."),
            ("let down", "disappoint", "məyus etmək, ümidini puça çıxarmaq", "Don't let me down."),
            ("go through", "experience something hard", "başından keçirmək", "She went through a difficult time."),
            ("open up", "start talking about feelings", "ürəyini açmaq", "He finally opened up to me."),
        ],
        phrases=[
            ("We fell out, but we made up the next day.", "a fight and peace", "Küsdük, amma ertəsi gün barışdıq."),
            ("Cheer up - it'll be fine.", "comforting someone", "Kefini pozma, hər şey yaxşı olacaq."),
            ("Just calm down for a second.", "stopping panic", "Bir saniyə sakitləş."),
            ("I felt really let down.", "disappointed", "Özümü çox məyus hiss etdim."),
            ("She's going through a lot right now.", "a hard time", "O, hazırda çox şey yaşayır."),
        ],
        grammar={
            "name": "Phrasal verbs with feelings: make someone ...",
            "rule": ("Some phrasal verbs work in two ways: 'I cheered up' (I became happier) and 'She cheered me up' "
                     "(she made me happier). With a person in the middle: cheer him up, calm her down, let them down."),
            "table": ["I cheered up. / She cheered me up.", "calm down / calm someone down",
                      "let someone down (never: let down him)"],
            "examples": [("A walk always cheers me up.", ""),
                         ("I tried to calm him down.", ""),
                         ("I promise I won't let you down.", "")],
        },
        skills=["phrasal_verbs"],
        partner_role="friend",
        dialogue=[
            ("partner", "You look sad. What's wrong?"),
            ("learner", "I fell out with my best friend yesterday."),
            ("partner", "Oh no. What happened?"),
            ("learner", "He let me down. He forgot my birthday."),
            ("partner", "Cheer up. Call him - I'm sure you'll make up."),
            ("learner", "You're right. I'll calm down first and then call him."),
        ],
        build=[
            ("Say it with a phrasal verb: We became friends again.", "We made up."),
            ("Say it with a phrasal verb and 'me': The film made me happier.", "The film cheered me up."),
            ("Say it with a phrasal verb: He disappointed his team.", "He let his team down."),
            ("Join with 'but': We had an argument. We made up the next day.", "We had an argument, but we made up the next day."),
        ],
        questions=[
            ("What cheers you up when you feel down?", "Music and a walk by the river always cheer me up."),
            ("Tell me about a time you fell out with someone and made up.", "I fell out with my brother, but we made up after a week."),
        ],
        speak="Tell a story about a friendship: an argument, how you calmed down, how you made up.",
    ),
    _lesson(
        "en-i19", 4, 4, "B1", "Travel - check in, get around, set off",
        "talk about travel with phrasal verbs",
        words=[
            ("check in / check out", "arrive at / leave a hotel or airport", "qeydiyyatdan keçmək / otaqdan çıxmaq", "We checked in at noon."),
            ("get around", "travel in a place", "gəzmək, hərəkət etmək", "It's easy to get around by tram."),
            ("set off", "start a journey", "yola düşmək", "We set off at dawn."),
            ("take off", "leave the ground (a plane)", "havaya qalxmaq", "The plane took off late."),
            ("pick up", "collect someone by car", "götürmək (maşınla)", "I'll pick you up at the airport."),
            ("drop off", "take someone somewhere and leave", "düşürmək, aparıb qoymaq", "Can you drop me off at the station?"),
            ("look around", "visit and see a place", "ətrafa baxmaq, gəzmək", "We looked around the old town."),
        ],
        phrases=[
            ("What time do we need to check in?", "at the airport or hotel", "Saat neçədə qeydiyyatdan keçməliyik?"),
            ("I'll pick you up at eight.", "offering a lift", "Səni səkkizdə götürəcəm."),
            ("Could you drop me off here?", "in a taxi", "Məni burada düşürə bilərsiniz?"),
            ("The best way to get around is by bike.", "local transport", "Gəzməyin ən yaxşı yolu velosipeddir."),
            ("We just looked around the market.", "sightseeing", "Sadəcə bazarı gəzdik."),
        ],
        grammar={
            "name": "Phrasal verbs as nouns",
            "rule": ("Some phrasal verbs become nouns: check in → the check-in, take off → the take-off, set up → "
                     "the setup. 'Check-in closes at 10.' As verbs they have two words: 'We check in at 10.'"),
            "table": ["verb: we check in · noun: the check-in", "verb: the plane takes off · noun: take-off"],
            "examples": [("We checked in two hours early.", ""),
                         ("Check-in closes forty minutes before the flight.", ""),
                         ("My brother picked me up from the airport.", "")],
        },
        skills=["phrasal_verbs"],
        partner_role="hotel receptionist",
        dialogue=[
            ("partner", "Good afternoon. Are you checking in?"),
            ("learner", "Yes, please. I booked a room for two nights."),
            ("partner", "Here's your key. Check-out is at eleven."),
            ("learner", "Thanks. What's the best way to get around the city?"),
            ("partner", "The tram. You can also look around the old town on foot."),
            ("learner", "Great. Could you call a taxi to pick me up at nine tomorrow?"),
        ],
        build=[
            ("Say it with a phrasal verb: We arrived at the hotel and got our key.", "We checked in at the hotel."),
            ("Say it with a phrasal verb: I'll collect you at the airport.", "I'll pick you up at the airport."),
            ("Say it with a phrasal verb: The plane left the ground late.", "The plane took off late."),
            ("Join with 'so that': We set off early. We could avoid the traffic.", "We set off early so that we could avoid the traffic."),
        ],
        questions=[
            ("How do you usually get around your city?", "I usually get around by tram, but sometimes I cycle."),
            ("Tell me about your last trip from the start.", "We set off at six, checked in at the airport, and the plane took off on time."),
        ],
        speak="Tell the story of a trip from leaving home to coming back, with at least six travel phrasal verbs.",
    ),
    _lesson(
        "en-i20", 4, 5, "B1", "B1 final - talk like a native",
        "speak for several minutes with linking words and phrasal verbs",
        words=[
            ("to sum up", "to finish with the main idea", "yekun olaraq", "To sum up, it was a great year."),
            ("what's more", "and also (stronger)", "üstəlik", "What's more, it's free."),
            ("in my view", "in my opinion", "məncə, fikrimcə", "In my view, it's worth it."),
            ("as far as I know", "I think this is true", "bildiyimə görə", "As far as I know, it opens at nine."),
            ("look back on", "remember the past", "geriyə baxmaq, xatırlamaq", "I look back on that year with joy."),
            ("move on", "go to the next stage", "irəli getmək, keçmək", "It's time to move on."),
        ],
        phrases=[
            ("When I look back on it, I learned a lot.", "reflecting", "Geriyə baxanda çox şey öyrəndim."),
            ("In my view, the best part was ...", "an opinion", "Məncə, ən yaxşı hissəsi ... idi."),
            ("What's more, I made new friends.", "adding something good", "Üstəlik, yeni dostlar qazandım."),
            ("To sum up, I'm really glad I did it.", "ending", "Yekun olaraq, bunu etdiyimə çox şadam."),
            ("Now it's time to move on to the next step.", "the future", "İndi növbəti addıma keçmək vaxtıdır."),
        ],
        grammar={
            "name": "A fluent answer: structure",
            "rule": ("A strong B1 answer has a shape: an opinion (in my view), a reason (because), an example "
                     "(for example / when I...), a contrast (although / however), and an ending (to sum up). "
                     "Add phrasal verbs where they sound natural."),
            "table": ["In my view, ... because ...", "For example, when I ... / Although ...",
                      "What's more, ... To sum up, ..."],
            "examples": [("In my view, learning online is great because it's flexible.", ""),
                         ("Although it's hard to stay motivated, I never give up.", ""),
                         ("To sum up, it has changed my life.", "")],
        },
        skills=["linking_words", "phrasal_verbs", "discourse_markers"],
        partner_role="examiner",
        dialogue=[
            ("partner", "How has your English changed this month?"),
            ("learner", "When I look back on it, I can see a big difference."),
            ("partner", "What was the hardest part?"),
            ("learner", "At first, phrasal verbs were hard. However, I didn't give up."),
            ("partner", "And what's next for you?"),
            ("learner", "To sum up, I'm ready to move on to B2, so that I can speak freely at work."),
        ],
        build=[
            ("Join with 'although' and 'give up': It was hard. I didn't stop trying.", "Although it was hard, I didn't give up."),
            ("Start with 'In my view' and add a reason: Online courses are good. They are flexible.", "In my view, online courses are good because they are flexible."),
            ("Add with 'What's more': The course is cheap. It's very useful.", "The course is cheap. What's more, it's very useful."),
            ("End with 'To sum up': I'm glad I started.", "To sum up, I'm glad I started."),
        ],
        questions=[
            ("Is it better to learn a language at home or abroad? Why?", "In my view, abroad is better because you have to speak every day. However, it's expensive."),
            ("What will you do next to improve your English?", "I'm going to carry on speaking every day so that I can move on to B2."),
        ],
        speak=("Final B1 test, about 5 minutes: give your opinion on a topic with reasons, examples and a contrast, "
               "then tell a story with phrasal verbs. The tutor only asks follow-up questions, then gives feedback: "
               "two strong points and two things to practise."),
    ),
]

COURSE = {
    "id": "english_sentences",
    "language": "english",
    "about": ("For learners with basic English: make your sentences longer and more natural with "
              "linking words and phrasal verbs - A2 to B1 in four weeks."),
    "learner": ("The learner already speaks basic English (A2). This course makes their sentences "
                "longer and more natural: linking words and phrasal verbs."),
    "title": "English · A2 → B1 · Sentence builder",
    "weeks": [
        {"week": 1, "title": "Joining ideas", "band": "A2"},
        {"week": 2, "title": "Everyday phrasal verbs", "band": "A2"},
        {"week": 3, "title": "Longer sentences", "band": "B1"},
        {"week": 4, "title": "Phrasal verbs for fluent talk", "band": "B1"},
    ],
    "lessons": LESSONS,
}
