"""
tutor/intensive_slovak.py - the intensive Slovak course: 6 weeks, A1 to B1.

Written for a learner who knows NO Slovak at all. Six weeks, five lessons a
week. Every lesson is a fixed piece of material the tutor follows step by
step: a review of earlier words, new words, ready phrases, one grammar point,
a dialogue, translation drills, questions about the learner's own life and a
speaking task. Weeks 1-2 are A1 (explained in simple English), weeks 3-4 are
A2 and weeks 5-6 are B1 (explained in simple Slovak).

Every item is (Slovak, English, Azerbaijani). The learner is a man, so the
examples use the masculine forms; the rule says the feminine one.
"""
from __future__ import annotations


def _items(rows: list[tuple[str, str, str]]) -> list[dict]:
    return [{"text": sk, "meaning": en, "native": az} for sk, en, az in rows]


def _lesson(lid: str, week: int, day: int, band: str, title: str, goal: str,
            words: list, phrases: list, grammar: dict, partner_role: str,
            dialogue: list, translate: list, questions: list, speak: str,
            skills: list[str] | None = None) -> dict:
    return {
        "id": lid, "week": week, "day": day, "band": band, "title": title, "goal": goal,
        "words": _items(words), "phrases": _items(phrases),
        "grammar": dict(grammar, skills=skills or []),
        "partner_role": partner_role,
        "dialogue": [{"who": who, "text": sk, "meaning": en} for who, sk, en in dialogue],
        "translate": [{"en": en, "sk": sk} for en, sk in translate],
        "questions": [{"q": q, "meaning": en, "example": ex} for q, en, ex in questions],
        "speak": speak,
    }


LESSONS: list[dict] = [
    # ══ WEEK 1 - A1: me and my world ═════════════════════════════════════════
    _lesson(
        "sk-i01", 1, 1, "A1", "Ahoj! Hello and my name",
        "say hello and goodbye, say your name, ask someone's name",
        words=[
            ("ahoj", "hi / bye (friends)", "salam / sağ ol"),
            ("dobrý deň", "good day, hello (polite)", "salam, gününüz xeyir"),
            ("dobré ráno", "good morning", "sabahınız xeyir"),
            ("dobrý večer", "good evening", "axşamınız xeyir"),
            ("dovidenia", "goodbye (polite)", "sağ olun, görüşənədək"),
            ("ďakujem", "thank you", "təşəkkür edirəm"),
            ("prosím", "please / you're welcome", "zəhmət olmasa / buyurun"),
            ("áno / nie", "yes / no", "bəli / xeyr"),
        ],
        phrases=[
            ("Volám sa Taleh.", "My name is Taleh.", "Mənim adım Talehdir."),
            ("Ako sa voláš?", "What is your name? (friend)", "Adın nədir?"),
            ("Teší ma.", "Nice to meet you.", "Tanış olduğuma şadam."),
            ("Ako sa máš?", "How are you?", "Necəsən?"),
            ("Mám sa dobre.", "I am fine.", "Yaxşıyam."),
        ],
        grammar={
            "name": "Volám sa ... / Ako sa voláš?",
            "rule": ("To say your name: 'Volám sa' + name. To ask a friend: 'Ako sa voláš?'. "
                     "To ask politely: 'Ako sa voláte?'. 'sa' is a small word that stays with the verb."),
            "table": ["ja: volám sa - I am called", "ty: voláš sa - you are called",
                      "vy: voláte sa - you are called (polite)"],
            "examples": [("Volám sa Taleh.", "My name is Taleh."),
                         ("Ako sa voláš?", "What is your name?"),
                         ("Ako sa voláte?", "What is your name? (polite)")],
        },
        skills=["sk_reflexive"],
        partner_role="new friend",
        dialogue=[
            ("partner", "Ahoj! Ako sa voláš?", "Hi! What is your name?"),
            ("learner", "Ahoj! Volám sa Taleh. A ty?", "Hi! My name is Taleh. And you?"),
            ("partner", "Volám sa Peter. Teší ma.", "My name is Peter. Nice to meet you."),
            ("learner", "Aj mňa teší. Ako sa máš?", "Nice to meet you too. How are you?"),
            ("partner", "Mám sa dobre, ďakujem.", "I am fine, thank you."),
            ("learner", "Aj ja. Ahoj!", "Me too. Bye!"),
        ],
        translate=[
            ("Good day.", "Dobrý deň."),
            ("My name is Taleh.", "Volám sa Taleh."),
            ("Nice to meet you.", "Teší ma."),
            ("Thank you, goodbye.", "Ďakujem, dovidenia."),
        ],
        questions=[
            ("Ako sa voláš?", "What is your name?", "Volám sa Taleh."),
            ("Ako sa máš?", "How are you?", "Mám sa dobre, ďakujem."),
        ],
        speak="Meet the tutor as a new person: say hello, your name, ask their name, how they are, say goodbye.",
    ),
    _lesson(
        "sk-i02", 1, 2, "A1", "Odkiaľ si? Where are you from?",
        "say where you are from and where you live; the verb byť (to be)",
        words=[
            ("Azerbajdžan", "Azerbaijan", "Azərbaycan"),
            ("Slovensko", "Slovakia", "Slovakiya"),
            ("Baku", "Baku", "Bakı"),
            ("Bratislava", "Bratislava", "Bratislava"),
            ("mesto", "city", "şəhər"),
            ("krajina", "country", "ölkə"),
            ("tu", "here", "burada"),
            ("teraz", "now", "indi"),
        ],
        phrases=[
            ("Odkiaľ si?", "Where are you from?", "Haralısan?"),
            ("Som z Azerbajdžanu.", "I am from Azerbaijan.", "Mən Azərbaycandanam."),
            ("Bývam v Bratislave.", "I live in Bratislava.", "Mən Bratislavada yaşayıram."),
            ("Kde bývaš?", "Where do you live?", "Harada yaşayırsan?"),
            ("Som tu nový.", "I am new here.", "Mən burada yeniyəm."),
        ],
        grammar={
            "name": "byť - to be",
            "rule": ("'byť' means 'to be'. It changes with the person: ja som, ty si, on je. "
                     "You do not need 'ja' - 'Som Taleh' is enough, the verb shows the person."),
            "table": ["ja som · ty si · on / ona je", "my sme · vy ste · oni sú"],
            "examples": [("Som z Baku.", "I am from Baku."),
                         ("Odkiaľ si?", "Where are you from?"),
                         ("Peter je zo Slovenska.", "Peter is from Slovakia.")],
        },
        skills=["sk_byt"],
        partner_role="neighbour",
        dialogue=[
            ("partner", "Dobrý deň. Ste tu nový?", "Good day. Are you new here?"),
            ("learner", "Dobrý deň. Áno, som tu nový.", "Good day. Yes, I am new here."),
            ("partner", "Odkiaľ ste?", "Where are you from?"),
            ("learner", "Som z Azerbajdžanu, z Baku.", "I am from Azerbaijan, from Baku."),
            ("partner", "A kde teraz bývate?", "And where do you live now?"),
            ("learner", "Teraz bývam tu, v Bratislave.", "Now I live here, in Bratislava."),
        ],
        translate=[
            ("I am from Azerbaijan.", "Som z Azerbajdžanu."),
            ("Where are you from?", "Odkiaľ si?"),
            ("I live in Bratislava.", "Bývam v Bratislave."),
            ("We are here.", "Sme tu."),
        ],
        questions=[
            ("Odkiaľ si?", "Where are you from?", "Som z Azerbajdžanu."),
            ("Kde bývaš teraz?", "Where do you live now?", "Teraz bývam v Bratislave."),
            ("Si tu nový?", "Are you new here?", "Áno, som tu nový."),
        ],
        speak="Introduce yourself: name, where you are from, where you live now.",
    ),
    _lesson(
        "sk-i03", 1, 3, "A1", "Čísla - numbers and my age",
        "count 0-20, say your age and phone number; the verb mať (to have)",
        words=[
            ("jeden, dva, tri", "one, two, three", "bir, iki, üç"),
            ("štyri, päť, šesť", "four, five, six", "dörd, beş, altı"),
            ("sedem, osem, deväť", "seven, eight, nine", "yeddi, səkkiz, doqquz"),
            ("desať", "ten", "on"),
            ("jedenásť, dvanásť", "eleven, twelve", "on bir, on iki"),
            ("dvadsať, tridsať", "twenty, thirty", "iyirmi, otuz"),
            ("rok / roky", "year / years", "il / illər"),
            ("telefónne číslo", "phone number", "telefon nömrəsi"),
        ],
        phrases=[
            ("Koľko máš rokov?", "How old are you?", "Neçə yaşın var?"),
            ("Mám tridsať rokov.", "I am thirty.", "Otuz yaşım var."),
            ("Aké je tvoje číslo?", "What is your number?", "Nömrən neçədir?"),
            ("Moje číslo je ...", "My number is ...", "Mənim nömrəm ..."),
            ("Ešte raz, prosím.", "Once more, please.", "Bir də, zəhmət olmasa."),
        ],
        grammar={
            "name": "mať - to have",
            "rule": ("'mať' means 'to have'. Slovaks HAVE years: 'Mám tridsať rokov' = I am thirty. "
                     "After 2, 3, 4 we say 'roky', after 5 and more 'rokov'."),
            "table": ["ja mám · ty máš · on / ona má", "my máme · vy máte · oni majú"],
            "examples": [("Mám tridsať rokov.", "I am thirty."),
                         ("Koľko máš rokov?", "How old are you?"),
                         ("Mám telefón.", "I have a phone.")],
        },
        skills=["sk_mat", "sk_numbers"],
        partner_role="clerk at an office",
        dialogue=[
            ("partner", "Dobrý deň. Ako sa voláte?", "Good day. What is your name?"),
            ("learner", "Volám sa Taleh Rzayev.", "My name is Taleh Rzayev."),
            ("partner", "Koľko máte rokov?", "How old are you?"),
            ("learner", "Mám tridsať rokov.", "I am thirty."),
            ("partner", "Aké je vaše telefónne číslo?", "What is your phone number?"),
            ("learner", "Moje číslo je nula, deväť, jeden, dva...", "My number is zero, nine, one, two..."),
        ],
        translate=[
            ("I have a phone.", "Mám telefón."),
            ("How old are you?", "Koľko máš rokov?"),
            ("I am thirty years old.", "Mám tridsať rokov."),
            ("Once more, please.", "Ešte raz, prosím."),
        ],
        questions=[
            ("Koľko máš rokov?", "How old are you?", "Mám tridsať rokov."),
            ("Aké je tvoje telefónne číslo?", "What is your phone number?", "Moje číslo je nula, deväť..."),
        ],
        speak="Count from one to twenty with the tutor, then say your name, age and phone number.",
    ),
    _lesson(
        "sk-i04", 1, 4, "A1", "Moja rodina - my family",
        "talk about your family; môj / moja / moje (my)",
        words=[
            ("mama", "mother", "ana"),
            ("otec", "father", "ata"),
            ("brat", "brother", "qardaş"),
            ("sestra", "sister", "bacı"),
            ("manželka", "wife", "həyat yoldaşı (qadın)"),
            ("syn / dcéra", "son / daughter", "oğul / qız"),
            ("deti", "children", "uşaqlar"),
            ("rodina", "family", "ailə"),
        ],
        phrases=[
            ("Mám brata a sestru.", "I have a brother and a sister.", "Bir qardaşım və bir bacım var."),
            ("Toto je môj otec.", "This is my father.", "Bu mənim atamdır."),
            ("Moja mama sa volá ...", "My mother's name is ...", "Anamın adı ...dır."),
            ("Máš deti?", "Do you have children?", "Uşaqların var?"),
            ("Nemám deti.", "I don't have children.", "Uşaqlarım yoxdur."),
        ],
        grammar={
            "name": "môj, moja, moje - my",
            "rule": ("Every Slovak noun is 'he', 'she' or 'it'. 'my' changes with it: môj brat (he), "
                     "moja sestra (she, ends in -a), moje mesto (it, ends in -o). 'Nemám' = I don't have."),
            "table": ["on: môj brat, môj otec", "ona: moja mama, moja sestra", "ono: moje mesto, moje auto"],
            "examples": [("To je môj brat.", "This is my brother."),
                         ("Moja sestra býva v Baku.", "My sister lives in Baku."),
                         ("Moje mesto je veľké.", "My city is big.")],
        },
        skills=["sk_possessive", "sk_gender"],
        partner_role="friend looking at photos",
        dialogue=[
            ("partner", "Kto je to na fotke?", "Who is that in the photo?"),
            ("learner", "To je moja rodina. Toto je môj otec.", "That is my family. This is my father."),
            ("partner", "A kto je toto?", "And who is this?"),
            ("learner", "To je moja sestra. Volá sa Aysel.", "That is my sister. Her name is Aysel."),
            ("partner", "Máš aj brata?", "Do you also have a brother?"),
            ("learner", "Áno, mám brata. Býva v Baku.", "Yes, I have a brother. He lives in Baku."),
        ],
        translate=[
            ("This is my mother.", "To je moja mama."),
            ("I have a brother.", "Mám brata."),
            ("My sister lives in Baku.", "Moja sestra býva v Baku."),
            ("I don't have children.", "Nemám deti."),
        ],
        questions=[
            ("Máš brata alebo sestru?", "Do you have a brother or a sister?", "Mám brata a sestru."),
            ("Ako sa volá tvoja mama?", "What is your mother's name?", "Moja mama sa volá ..."),
            ("Kde býva tvoja rodina?", "Where does your family live?", "Moja rodina býva v Baku."),
        ],
        speak="Describe your family: who they are, their names, where they live.",
    ),
    _lesson(
        "sk-i05", 1, 5, "A1", "Práca a jazyky - job and languages",
        "say what you do and which languages you speak; present tense verbs",
        words=[
            ("práca", "work, job", "iş"),
            ("programátor", "programmer", "proqramçı"),
            ("inžinier", "engineer", "mühəndis"),
            ("firma", "company", "şirkət"),
            ("jazyk", "language", "dil"),
            ("po slovensky", "in Slovak", "slovakca"),
            ("po anglicky", "in English", "ingiliscə"),
            ("trochu", "a little", "bir az"),
        ],
        phrases=[
            ("Čo robíš?", "What do you do?", "Nə işlə məşğulsan?"),
            ("Som programátor.", "I am a programmer.", "Mən proqramçıyam."),
            ("Pracujem v IT firme.", "I work in an IT company.", "IT şirkətində işləyirəm."),
            ("Hovorím po anglicky.", "I speak English.", "İngiliscə danışıram."),
            ("Učím sa po slovensky.", "I am learning Slovak.", "Slovakca öyrənirəm."),
        ],
        grammar={
            "name": "Present tense: -ám, -ím, -em",
            "rule": ("Slovak verbs change their ending for each person. For 'I' the ending is "
                     "-m: volám, hovorím, pracujem. For 'you' (friend) it is -š: voláš, hovoríš, pracuješ."),
            "table": ["hovoriť: hovorím, hovoríš, hovorí", "pracovať: pracujem, pracuješ, pracuje",
                      "robiť: robím, robíš, robí"],
            "examples": [("Pracujem v IT firme.", "I work in an IT company."),
                         ("Hovoríš po slovensky?", "Do you speak Slovak?"),
                         ("Peter pracuje v banke.", "Peter works in a bank.")],
        },
        skills=["sk_present"],
        partner_role="colleague",
        dialogue=[
            ("partner", "Čo robíš, Taleh?", "What do you do, Taleh?"),
            ("learner", "Som programátor. Pracujem v IT firme.", "I am a programmer. I work in an IT company."),
            ("partner", "Hovoríš po slovensky?", "Do you speak Slovak?"),
            ("learner", "Trochu. Učím sa po slovensky.", "A little. I am learning Slovak."),
            ("partner", "A aké jazyky hovoríš?", "And which languages do you speak?"),
            ("learner", "Hovorím po azerbajdžansky, po anglicky a trochu po slovensky.",
             "I speak Azerbaijani, English and a little Slovak."),
        ],
        translate=[
            ("I am a programmer.", "Som programátor."),
            ("I work in a company.", "Pracujem vo firme."),
            ("Do you speak English?", "Hovoríš po anglicky?"),
            ("I speak a little Slovak.", "Hovorím trochu po slovensky."),
        ],
        questions=[
            ("Čo robíš?", "What do you do?", "Som programátor."),
            ("Kde pracuješ?", "Where do you work?", "Pracujem v IT firme."),
            ("Aké jazyky hovoríš?", "Which languages do you speak?", "Hovorím po anglicky a trochu po slovensky."),
        ],
        speak="Talk for one minute about yourself: name, country, city, family, job, languages. The tutor helps.",
    ),

    # ══ WEEK 2 - A1: every day ═══════════════════════════════════════════════
    _lesson(
        "sk-i06", 2, 1, "A1", "Môj deň - my day",
        "tell the time and describe your daily routine; verbs with sa",
        words=[
            ("ráno", "morning, in the morning", "səhər"),
            ("večer", "evening, in the evening", "axşam"),
            ("vstávať", "to get up", "yuxudan durmaq"),
            ("raňajkovať", "to have breakfast", "səhər yeməyi yemək"),
            ("obed", "lunch", "nahar"),
            ("večera", "dinner", "şam yeməyi"),
            ("hodina", "hour, o'clock", "saat"),
            ("potom", "then, after that", "sonra"),
        ],
        phrases=[
            ("Koľko je hodín?", "What time is it?", "Saat neçədir?"),
            ("Je osem hodín.", "It is eight o'clock.", "Saat səkkizdir."),
            ("Vstávam o siedmej.", "I get up at seven.", "Saat yeddidə dururam."),
            ("Idem do práce.", "I go to work.", "İşə gedirəm."),
            ("Idem spať o jedenástej.", "I go to sleep at eleven.", "Saat on birdə yatıram."),
        ],
        grammar={
            "name": "Verbs with sa (umývam sa, obliekam sa)",
            "rule": ("Some verbs need 'sa': umývať sa (to wash yourself), obliekať sa (to get dressed), "
                     "učiť sa (to learn). 'sa' usually stands in the second place of the sentence."),
            "table": ["umývam sa · obliekam sa · učím sa", "Ráno sa umývam. (sa = 2nd place)"],
            "examples": [("Ráno sa umývam a obliekam.", "In the morning I wash and get dressed."),
                         ("Večer sa učím po slovensky.", "In the evening I learn Slovak."),
                         ("Potom sa obliekam.", "Then I get dressed.")],
        },
        skills=["sk_reflexive", "sk_word_order"],
        partner_role="friend",
        dialogue=[
            ("partner", "Kedy ráno vstávaš?", "When do you get up in the morning?"),
            ("learner", "Vstávam o siedmej.", "I get up at seven."),
            ("partner", "A čo robíš potom?", "And what do you do then?"),
            ("learner", "Umývam sa, raňajkujem a idem do práce.", "I wash, have breakfast and go to work."),
            ("partner", "Čo robíš večer?", "What do you do in the evening?"),
            ("learner", "Večer sa učím po slovensky.", "In the evening I learn Slovak."),
        ],
        translate=[
            ("What time is it?", "Koľko je hodín?"),
            ("I get up at seven.", "Vstávam o siedmej."),
            ("Then I go to work.", "Potom idem do práce."),
            ("In the evening I learn Slovak.", "Večer sa učím po slovensky."),
        ],
        questions=[
            ("Kedy vstávaš?", "When do you get up?", "Vstávam o siedmej."),
            ("Čo robíš ráno?", "What do you do in the morning?", "Ráno sa umývam a raňajkujem."),
            ("Kedy ideš spať?", "When do you go to sleep?", "Idem spať o jedenástej."),
        ],
        speak="Describe your whole day from morning to night with times, using potom (then).",
    ),
    _lesson(
        "sk-i07", 2, 2, "A1", "V kaviarni - in the café",
        "order food and drink, pay; the accusative after dám si / chcem",
        words=[
            ("káva", "coffee", "qəhvə"),
            ("čaj", "tea", "çay"),
            ("voda", "water", "su"),
            ("mlieko", "milk", "süd"),
            ("cukor", "sugar", "şəkər"),
            ("koláč", "cake", "tort, pirojna"),
            ("polievka", "soup", "şorba"),
            ("účet", "bill", "hesab"),
        ],
        phrases=[
            ("Dám si kávu, prosím.", "I'll have a coffee, please.", "Bir qəhvə alaram, zəhmət olmasa."),
            ("S mliekom, bez cukru.", "With milk, without sugar.", "Südlü, şəkərsiz."),
            ("Koľko to stojí?", "How much is it?", "Bu neçəyədir?"),
            ("Zaplatím, prosím.", "I'd like to pay, please.", "Hesabı verin, zəhmət olmasa."),
            ("Môžem platiť kartou?", "Can I pay by card?", "Kartla ödəyə bilərəm?"),
        ],
        grammar={
            "name": "What do you want? káva → kávu",
            "rule": ("After 'Dám si' (I'll have) and 'Chcem' (I want) a word ending in -a changes "
                     "to -u: káva → kávu, voda → vodu. Words like čaj, koláč, pivo do not change."),
            "table": ["-a → -u: káva → kávu, polievka → polievku", "no change: čaj, koláč, mlieko"],
            "examples": [("Dám si kávu.", "I'll have a coffee."),
                         ("Chcem vodu.", "I want water."),
                         ("Dám si čaj a koláč.", "I'll have a tea and a cake.")],
        },
        skills=["sk_accusative", "sk_modals"],
        partner_role="waiter",
        dialogue=[
            ("partner", "Dobrý deň. Čo si dáte?", "Good day. What will you have?"),
            ("learner", "Dám si kávu, prosím.", "I'll have a coffee, please."),
            ("partner", "S mliekom?", "With milk?"),
            ("learner", "Áno, s mliekom, bez cukru. A jeden koláč.", "Yes, with milk, no sugar. And one cake."),
            ("partner", "Nech sa páči. Ešte niečo?", "Here you are. Anything else?"),
            ("learner", "Nie, ďakujem. Zaplatím, prosím.", "No, thank you. I'd like to pay, please."),
        ],
        translate=[
            ("I'll have a tea, please.", "Dám si čaj, prosím."),
            ("I want water.", "Chcem vodu."),
            ("Without sugar.", "Bez cukru."),
            ("Can I pay by card?", "Môžem platiť kartou?"),
        ],
        questions=[
            ("Čo si dáš ráno?", "What do you have in the morning?", "Ráno si dám kávu."),
            ("Piješ kávu s mliekom?", "Do you drink coffee with milk?", "Áno, pijem kávu s mliekom."),
        ],
        speak="Role play in a café: the tutor is the waiter. Order a drink and food, ask the price, pay.",
    ),
    _lesson(
        "sk-i08", 2, 3, "A1", "V obchode - shopping and prices",
        "numbers to 100, prices, buy things; plural and 1 / 2-4 / 5+",
        words=[
            ("obchod", "shop", "mağaza"),
            ("euro / eurá / eur", "euro", "avro"),
            ("chlieb", "bread", "çörək"),
            ("jablko / jablká", "apple / apples", "alma / almalar"),
            ("vajce / vajcia", "egg / eggs", "yumurta / yumurtalar"),
            ("štyridsať, päťdesiat", "forty, fifty", "qırx, əlli"),
            ("sto", "one hundred", "yüz"),
            ("lacný / drahý", "cheap / expensive", "ucuz / baha"),
        ],
        phrases=[
            ("Koľko stojí chlieb?", "How much is the bread?", "Çörək neçəyədir?"),
            ("Stojí to dve eurá.", "It costs two euros.", "İki avrodur."),
            ("Máte mlieko?", "Do you have milk?", "Süd var?"),
            ("Hľadám ...", "I am looking for ...", "... axtarıram"),
            ("Zoberiem si to.", "I'll take it.", "Bunu götürürəm."),
        ],
        grammar={
            "name": "1 euro, 2 eurá, 5 eur",
            "rule": ("After 1: one thing (jedno euro). After 2, 3, 4: the plural (dve eurá, tri jablká). "
                     "After 5 and more: another form (päť eur, desať jabĺk). 'dva' becomes 'dve' for she/it words."),
            "table": ["1: jedno euro · jedno jablko", "2-4: dve eurá · tri jablká",
                      "5+: päť eur · šesť jabĺk"],
            "examples": [("Stojí to jedno euro.", "It costs one euro."),
                         ("Chlieb stojí dve eurá.", "The bread costs two euros."),
                         ("To je desať eur.", "That is ten euros.")],
        },
        skills=["sk_numbers", "sk_plural"],
        partner_role="shop assistant",
        dialogue=[
            ("partner", "Dobrý deň, čo si prosíte?", "Good day, what would you like?"),
            ("learner", "Dobrý deň. Máte chlieb?", "Good day. Do you have bread?"),
            ("partner", "Áno, tu je. Ešte niečo?", "Yes, here it is. Anything else?"),
            ("learner", "Tri jablká a mlieko, prosím.", "Three apples and milk, please."),
            ("partner", "To je spolu päť eur.", "That is five euros together."),
            ("learner", "Nech sa páči. Ďakujem, dovidenia.", "Here you are. Thank you, goodbye."),
        ],
        translate=[
            ("How much is it?", "Koľko to stojí?"),
            ("It costs two euros.", "Stojí to dve eurá."),
            ("Do you have bread?", "Máte chlieb?"),
            ("I'll take it.", "Zoberiem si to."),
        ],
        questions=[
            ("Čo kupuješ v obchode?", "What do you buy in the shop?", "Kupujem chlieb, mlieko a jablká."),
            ("Koľko stojí káva?", "How much does a coffee cost?", "Káva stojí dve eurá."),
        ],
        speak="Role play in a shop: buy three things, ask prices, count the money.",
    ),
    _lesson(
        "sk-i09", 2, 4, "A1", "V meste - in the city",
        "ask for and understand directions; v / na + place",
        words=[
            ("stanica", "station", "stansiya, vağzal"),
            ("zastávka", "(bus) stop", "dayanacaq"),
            ("centrum", "city centre", "mərkəz"),
            ("ulica", "street", "küçə"),
            ("rovno", "straight on", "düz"),
            ("doľava / doprava", "to the left / to the right", "sola / sağa"),
            ("blízko / ďaleko", "near / far", "yaxın / uzaq"),
            ("banka", "bank", "bank"),
        ],
        phrases=[
            ("Prepáčte, kde je stanica?", "Excuse me, where is the station?", "Bağışlayın, vağzal haradadır?"),
            ("Choďte rovno.", "Go straight on.", "Düz gedin."),
            ("Potom doľava.", "Then to the left.", "Sonra sola."),
            ("Je to ďaleko?", "Is it far?", "Uzaqdır?"),
            ("Je to blízko, päť minút.", "It is near, five minutes.", "Yaxındır, beş dəqiqəlik."),
        ],
        grammar={
            "name": "Where? v meste, na stanici",
            "rule": ("To say WHERE something is, use 'v' (in) or 'na' (on, at) and the end of the "
                     "word changes: mesto → v meste, stanica → na stanici, ulica → na ulici. Learn them as pairs."),
            "table": ["v centre · v meste · v banke", "na stanici · na zastávke · na ulici"],
            "examples": [("Som v centre.", "I am in the centre."),
                         ("Čakám na zastávke.", "I am waiting at the stop."),
                         ("Banka je na ulici Obchodná.", "The bank is on Obchodná street.")],
        },
        skills=["sk_locative", "sk_kde_kam"],
        partner_role="person on the street",
        dialogue=[
            ("learner", "Prepáčte, kde je stanica?", "Excuse me, where is the station?"),
            ("partner", "Choďte rovno a potom doprava.", "Go straight on and then to the right."),
            ("learner", "Je to ďaleko?", "Is it far?"),
            ("partner", "Nie, je to blízko. Desať minút pešo.", "No, it is near. Ten minutes on foot."),
            ("learner", "A kde je zastávka?", "And where is the stop?"),
            ("partner", "Zastávka je tam, pri banke.", "The stop is there, by the bank."),
        ],
        translate=[
            ("Excuse me, where is the bank?", "Prepáčte, kde je banka?"),
            ("Go straight on.", "Choďte rovno."),
            ("Is it far?", "Je to ďaleko?"),
            ("I am at the station.", "Som na stanici."),
        ],
        questions=[
            ("Kde bývaš - v centre?", "Where do you live - in the centre?", "Nie, nebývam v centre."),
            ("Je tvoja práca blízko alebo ďaleko?", "Is your work near or far?", "Moja práca je blízko."),
        ],
        speak="Ask the tutor the way to three places (station, bank, stop) and repeat the directions back.",
    ),
    _lesson(
        "sk-i10", 2, 5, "A1", "Voľný čas - free time and likes",
        "say what you like and don't like; rád + verb; negation ne-",
        words=[
            ("voľný čas", "free time", "boş vaxt"),
            ("čítať", "to read", "oxumaq"),
            ("variť", "to cook", "yemək bişirmək"),
            ("hudba", "music", "musiqi"),
            ("film", "film", "film"),
            ("šport", "sport", "idman"),
            ("víkend", "weekend", "həftəsonu"),
            ("často / niekedy", "often / sometimes", "tez-tez / bəzən"),
        ],
        phrases=[
            ("Rád čítam.", "I like reading.", "Oxumağı sevirəm."),
            ("Nerád varím.", "I don't like cooking.", "Yemək bişirməyi sevmirəm."),
            ("Čo rád robíš?", "What do you like doing?", "Nə etməyi sevirsən?"),
            ("Páči sa mi Bratislava.", "I like Bratislava.", "Bratislava xoşuma gəlir."),
            ("Cez víkend hrám futbal.", "At the weekend I play football.", "Həftəsonu futbol oynayıram."),
        ],
        grammar={
            "name": "rád + verb, ne- (not)",
            "rule": ("To say you like DOING something: rád (a man) / rada (a woman) + verb: Rád čítam. "
                     "To say 'not', put ne- in front of the verb, written together: nerád, nečítam, nemám."),
            "table": ["rád / rada + verb: rád čítam", "ne + verb: nečítam, nevarím, nie som"],
            "examples": [("Rád počúvam hudbu.", "I like listening to music."),
                         ("Nerád varím.", "I don't like cooking."),
                         ("Cez víkend nepracujem.", "At the weekend I don't work.")],
        },
        skills=["sk_negation"],
        partner_role="friend",
        dialogue=[
            ("partner", "Čo rád robíš vo voľnom čase?", "What do you like doing in your free time?"),
            ("learner", "Rád čítam a počúvam hudbu.", "I like reading and listening to music."),
            ("partner", "A rád varíš?", "And do you like cooking?"),
            ("learner", "Nie, nerád varím. Ale rád jem!", "No, I don't like cooking. But I like eating!"),
            ("partner", "Čo robíš cez víkend?", "What do you do at the weekend?"),
            ("learner", "Cez víkend často hrám futbal.", "At the weekend I often play football."),
        ],
        translate=[
            ("I like reading.", "Rád čítam."),
            ("I don't like cooking.", "Nerád varím."),
            ("At the weekend I don't work.", "Cez víkend nepracujem."),
            ("I like Bratislava.", "Páči sa mi Bratislava."),
        ],
        questions=[
            ("Čo rád robíš vo voľnom čase?", "What do you like doing in your free time?", "Rád čítam a hrám futbal."),
            ("Čo nerád robíš?", "What don't you like doing?", "Nerád varím."),
            ("Páči sa ti Bratislava?", "Do you like Bratislava?", "Áno, páči sa mi."),
        ],
        speak="Two weeks done! Talk about yourself: who you are, your day, your free time. Use a, ale, potom.",
    ),

    # ══ WEEK 3 - A2: past and future ═════════════════════════════════════════
    _lesson(
        "sk-i11", 3, 1, "A2", "Včera - yesterday",
        "say what you did yesterday; the past tense",
        words=[
            ("včera", "yesterday", "dünən"),
            ("predvčerom", "the day before yesterday", "srağagün"),
            ("bol som", "I was", "idim"),
            ("robil som", "I did / was doing", "edirdim / etdim"),
            ("išiel som", "I went", "getdim"),
            ("pozerať", "to watch", "baxmaq"),
            ("stretnúť", "to meet", "görüşmək"),
            ("celý deň", "all day", "bütün gün"),
        ],
        phrases=[
            ("Čo si robil včera?", "What did you do yesterday?", "Dünən nə etdin?"),
            ("Včera som pracoval.", "Yesterday I worked.", "Dünən işlədim."),
            ("Bol som doma.", "I was at home.", "Evdə idim."),
            ("Pozeral som film.", "I watched a film.", "Film izlədim."),
            ("Stretol som kamaráta.", "I met a friend.", "Bir dostla görüşdüm."),
        ],
        grammar={
            "name": "Minulý čas - the past tense",
            "rule": ("Minulý čas: sloveso bez -ť + -l a slovo 'som'. Pracovať → pracoval som. "
                     "Žena hovorí -la: pracovala som. Pri 'on' a 'ona' nie je 'som': on pracoval."),
            "table": ["ja: pracoval som · ty: pracoval si", "on: pracoval · ona: pracovala · oni: pracovali",
                      "byť → bol som · ísť → išiel som"],
            "examples": [("Včera som pracoval doma.", "Yesterday I worked at home."),
                         ("Čo si robil večer?", "What did you do in the evening?"),
                         ("Peter bol v Baku.", "Peter was in Baku.")],
        },
        skills=["sk_past"],
        partner_role="colleague on Monday",
        dialogue=[
            ("partner", "Ahoj! Čo si robil včera?", "Hi! What did you do yesterday?"),
            ("learner", "Ráno som bol doma a čítal som.", "In the morning I was at home and read."),
            ("partner", "A poobede?", "And in the afternoon?"),
            ("learner", "Poobede som išiel do centra a stretol som kamaráta.",
             "In the afternoon I went to the centre and met a friend."),
            ("partner", "A večer?", "And in the evening?"),
            ("learner", "Večer sme pozerali film.", "In the evening we watched a film."),
        ],
        translate=[
            ("Yesterday I was at home.", "Včera som bol doma."),
            ("I worked all day.", "Pracoval som celý deň."),
            ("What did you do yesterday?", "Čo si robil včera?"),
            ("I went to the shop.", "Išiel som do obchodu."),
        ],
        questions=[
            ("Čo si robil včera?", "What did you do yesterday?", "Včera som pracoval a večer som čítal."),
            ("Kde si bol v sobotu?", "Where were you on Saturday?", "V sobotu som bol v centre."),
            ("Čo si jedol na obed?", "What did you eat for lunch?", "Na obed som jedol polievku."),
        ],
        speak="Tell the tutor about yesterday from morning to evening, in the past tense.",
    ),
    _lesson(
        "sk-i12", 3, 2, "A2", "Môj víkend - my weekend story",
        "tell a short story in the past; linking words",
        words=[
            ("minulý týždeň", "last week", "keçən həftə"),
            ("v sobotu / v nedeľu", "on Saturday / on Sunday", "şənbə / bazar günü"),
            ("najprv", "first", "əvvəlcə"),
            ("potom", "then", "sonra"),
            ("nakoniec", "finally, in the end", "sonda"),
            ("ale", "but", "amma"),
            ("lebo", "because", "çünki"),
            ("výlet", "trip", "gəzinti, səfər"),
        ],
        phrases=[
            ("Aký bol víkend?", "How was your weekend?", "Həftəsonu necə keçdi?"),
            ("Bol super.", "It was great.", "Əla idi."),
            ("Najprv sme išli na výlet.", "First we went on a trip.", "Əvvəlcə gəzintiyə getdik."),
            ("Pršalo, preto sme boli doma.", "It rained, so we were at home.", "Yağış yağırdı, ona görə evdə qaldıq."),
            ("Bol som unavený, lebo som veľa pracoval.", "I was tired because I worked a lot.",
             "Yorğun idim, çünki çox işləmişdim."),
        ],
        grammar={
            "name": "Spájacie slová - najprv, potom, ale, lebo",
            "rule": ("Príbeh je lepší so spájacími slovami: najprv (first), potom (then), nakoniec (finally), "
                     "ale (but), lebo (because). Pred 'ale' a 'lebo' píšeme čiarku."),
            "table": ["najprv → potom → nakoniec", "..., ale ... · ..., lebo ..."],
            "examples": [("Najprv som raňajkoval, potom som išiel von.", "First I had breakfast, then I went out."),
                         ("Chcel som ísť von, ale pršalo.", "I wanted to go out, but it rained."),
                         ("Bol som doma, lebo som bol chorý.", "I was at home because I was ill.")],
        },
        skills=["sk_past", "sk_ze_aby"],
        partner_role="friend",
        dialogue=[
            ("partner", "Aký bol tvoj víkend?", "How was your weekend?"),
            ("learner", "Bol super. V sobotu sme išli na výlet do Tatier.",
             "It was great. On Saturday we went on a trip to the Tatras."),
            ("partner", "A čo ste robili?", "And what did you do?"),
            ("learner", "Najprv sme išli na kopec, potom sme obedovali.",
             "First we went up a hill, then we had lunch."),
            ("partner", "A v nedeľu?", "And on Sunday?"),
            ("learner", "V nedeľu som bol doma, lebo som bol unavený.", "On Sunday I was at home because I was tired."),
        ],
        translate=[
            ("How was your weekend?", "Aký bol tvoj víkend?"),
            ("First I cooked, then I read.", "Najprv som varil, potom som čítal."),
            ("I wanted to go out, but it rained.", "Chcel som ísť von, ale pršalo."),
            ("I was at home because I was tired.", "Bol som doma, lebo som bol unavený."),
        ],
        questions=[
            ("Aký bol tvoj víkend?", "How was your weekend?", "Bol dobrý. V sobotu som bol v centre."),
            ("Čo si robil minulý týždeň?", "What did you do last week?", "Minulý týždeň som veľa pracoval."),
        ],
        speak="Tell a story about your last weekend with najprv, potom, nakoniec, ale, lebo.",
    ),
    _lesson(
        "sk-i13", 3, 3, "A2", "Plány - plans for the future",
        "talk about plans; budem + verb, pôjdem",
        words=[
            ("zajtra", "tomorrow", "sabah"),
            ("pozajtra", "the day after tomorrow", "birigün"),
            ("budúci týždeň", "next week", "gələn həftə"),
            ("plán", "plan", "plan"),
            ("dovolenka", "holiday, vacation", "məzuniyyət"),
            ("cestovať", "to travel", "səyahət etmək"),
            ("navštíviť", "to visit", "ziyarət etmək"),
            ("možno", "maybe", "bəlkə"),
        ],
        phrases=[
            ("Čo budeš robiť zajtra?", "What will you do tomorrow?", "Sabah nə edəcəksən?"),
            ("Zajtra budem pracovať.", "Tomorrow I will work.", "Sabah işləyəcəyəm."),
            ("Pôjdem do Viedne.", "I will go to Vienna.", "Vyanaya gedəcəyəm."),
            ("Mám v pláne ...", "I plan to ...", "Planım ...dır"),
            ("Možno navštívim rodinu.", "Maybe I will visit my family.", "Bəlkə ailəmə baş çəkəcəyəm."),
        ],
        grammar={
            "name": "Budúci čas - budem + -ť",
            "rule": ("Budúci čas: budem, budeš, bude + sloveso na -ť: budem pracovať. "
                     "Ísť má vlastný tvar: pôjdem, pôjdeš, pôjde."),
            "table": ["budem, budeš, bude + -ť", "budeme, budete, budú + -ť", "ísť → pôjdem, pôjdeš"],
            "examples": [("Zajtra budem pracovať doma.", "Tomorrow I will work at home."),
                         ("Čo budeš robiť cez víkend?", "What will you do at the weekend?"),
                         ("Budúci týždeň pôjdem do Košíc.", "Next week I will go to Košice.")],
        },
        skills=["sk_future"],
        partner_role="friend",
        dialogue=[
            ("partner", "Čo budeš robiť cez víkend?", "What will you do at the weekend?"),
            ("learner", "V sobotu budem pracovať, ale v nedeľu mám voľno.",
             "On Saturday I will work, but on Sunday I am free."),
            ("partner", "A máš plány na leto?", "And do you have plans for the summer?"),
            ("learner", "Áno, pôjdem na dovolenku do Baku.", "Yes, I will go on holiday to Baku."),
            ("partner", "Super! Navštíviš rodinu?", "Great! Will you visit your family?"),
            ("learner", "Áno, budem tam dva týždne.", "Yes, I will be there for two weeks."),
        ],
        translate=[
            ("Tomorrow I will work.", "Zajtra budem pracovať."),
            ("What will you do at the weekend?", "Čo budeš robiť cez víkend?"),
            ("Next week I will go to Vienna.", "Budúci týždeň pôjdem do Viedne."),
            ("Maybe I will visit my family.", "Možno navštívim rodinu."),
        ],
        questions=[
            ("Čo budeš robiť zajtra?", "What will you do tomorrow?", "Zajtra budem pracovať."),
            ("Kam pôjdeš na dovolenku?", "Where will you go on holiday?", "Pôjdem do Baku."),
            ("Čo budeš robiť večer?", "What will you do in the evening?", "Večer sa budem učiť po slovensky."),
        ],
        speak="Tell the tutor your plans: tomorrow, this weekend, next month, the summer.",
    ),
    _lesson(
        "sk-i14", 3, 4, "A2", "Môj byt - my flat",
        "describe your home; where things are (v kuchyni, na stole)",
        words=[
            ("byt", "flat, apartment", "mənzil"),
            ("izba", "room", "otaq"),
            ("kuchyňa", "kitchen", "mətbəx"),
            ("kúpeľňa", "bathroom", "vanna otağı"),
            ("obývačka", "living room", "qonaq otağı"),
            ("stôl / stolička", "table / chair", "stol / stul"),
            ("posteľ", "bed", "çarpayı"),
            ("nájom", "rent", "kirayə"),
        ],
        phrases=[
            ("Bývam v malom byte.", "I live in a small flat.", "Kiçik bir mənzildə yaşayıram."),
            ("Môj byt má dve izby.", "My flat has two rooms.", "Mənzilim iki otaqlıdır."),
            ("V kuchyni je stôl.", "There is a table in the kitchen.", "Mətbəxdə stol var."),
            ("Kľúče sú na stole.", "The keys are on the table.", "Açarlar stolun üstündədir."),
            ("Nájom je drahý.", "The rent is expensive.", "Kirayə bahadır."),
        ],
        grammar={
            "name": "Kde to je? v kuchyni, na stole (6. pád)",
            "rule": ("Kde? v / na + 6. pád. Koncovka sa mení: kuchyňa → v kuchyni, izba → v izbe, "
                     "stôl → na stole, byt → v byte. 'Je' = there is (jedna vec), 'sú' = there are (viac vecí)."),
            "table": ["v kuchyni · v izbe · v byte · v obývačke", "na stole · na posteli · na stoličke"],
            "examples": [("V obývačke je gauč.", "There is a sofa in the living room."),
                         ("Kniha je na stole.", "The book is on the table."),
                         ("Bývam v byte v centre.", "I live in a flat in the centre.")],
        },
        skills=["sk_locative", "sk_adj_agreement"],
        partner_role="friend visiting",
        dialogue=[
            ("partner", "Aký je tvoj byt?", "What is your flat like?"),
            ("learner", "Je malý, ale pekný. Má dve izby.", "It is small but nice. It has two rooms."),
            ("partner", "Máš veľkú kuchyňu?", "Do you have a big kitchen?"),
            ("learner", "Nie, kuchyňa je malá. V kuchyni je len stôl a dve stoličky.",
             "No, the kitchen is small. In the kitchen there is only a table and two chairs."),
            ("partner", "A je byt drahý?", "And is the flat expensive?"),
            ("learner", "Áno, nájom je dosť drahý.", "Yes, the rent is quite expensive."),
        ],
        translate=[
            ("I live in a small flat.", "Bývam v malom byte."),
            ("There is a table in the kitchen.", "V kuchyni je stôl."),
            ("The keys are on the table.", "Kľúče sú na stole."),
            ("My flat has two rooms.", "Môj byt má dve izby."),
        ],
        questions=[
            ("Aký je tvoj byt?", "What is your flat like?", "Môj byt je malý, ale pekný."),
            ("Čo je v tvojej izbe?", "What is in your room?", "V mojej izbe je posteľ a stôl."),
        ],
        speak="Describe your flat room by room: what is where, what you like, what you don't like.",
    ),
    _lesson(
        "sk-i15", 3, 5, "A2", "U lekára - at the doctor",
        "say what hurts, make an appointment; musím, môžem",
        words=[
            ("lekár", "doctor", "həkim"),
            ("hlava", "head", "baş"),
            ("hrdlo", "throat", "boğaz"),
            ("brucho", "stomach", "qarın"),
            ("horúčka", "fever", "qızdırma"),
            ("chorý", "ill, sick", "xəstə"),
            ("liek / lieky", "medicine", "dərman"),
            ("lekáreň", "pharmacy", "aptek"),
        ],
        phrases=[
            ("Bolí ma hlava.", "I have a headache.", "Başım ağrıyır."),
            ("Mám horúčku.", "I have a fever.", "Qızdırmam var."),
            ("Som chorý.", "I am ill.", "Xəstəyəm."),
            ("Musím ísť k lekárovi.", "I must go to the doctor.", "Həkimə getməliyəm."),
            ("Môžem prísť zajtra?", "Can I come tomorrow?", "Sabah gələ bilərəm?"),
        ],
        grammar={
            "name": "musieť, môcť, chcieť + -ť",
            "rule": ("Po musím (I must), môžem (I can), chcem (I want) ide sloveso na -ť: "
                     "musím ísť, môžem prísť, chcem spať. 'Bolí ma' = mňa bolí (it hurts me)."),
            "table": ["musím · musíš · musí + -ť", "môžem · môžeš · môže + -ť", "chcem · chceš · chce + -ť"],
            "examples": [("Musím zostať doma.", "I must stay at home."),
                         ("Môžem prísť o desiatej?", "Can I come at ten?"),
                         ("Chcem sa objednať k lekárovi.", "I want to make a doctor's appointment.")],
        },
        skills=["sk_modals"],
        partner_role="doctor",
        dialogue=[
            ("partner", "Dobrý deň. Čo vás trápi?", "Good day. What is the problem?"),
            ("learner", "Dobrý deň. Bolí ma hlava a hrdlo.", "Good day. My head and throat hurt."),
            ("partner", "Máte horúčku?", "Do you have a fever?"),
            ("learner", "Áno, včera som mal horúčku.", "Yes, yesterday I had a fever."),
            ("partner", "Musíte zostať doma tri dni a brať tieto lieky.",
             "You must stay at home for three days and take this medicine."),
            ("learner", "Dobre. Môžem ísť do práce v piatok?", "OK. Can I go to work on Friday?"),
        ],
        translate=[
            ("I have a headache.", "Bolí ma hlava."),
            ("I am ill.", "Som chorý."),
            ("I must go to the doctor.", "Musím ísť k lekárovi."),
            ("Can I come tomorrow?", "Môžem prísť zajtra?"),
        ],
        questions=[
            ("Čo robíš, keď si chorý?", "What do you do when you are ill?", "Keď som chorý, zostanem doma."),
            ("Čo musíš robiť zajtra?", "What must you do tomorrow?", "Zajtra musím pracovať."),
        ],
        speak="Role play at the doctor: say what hurts, since when, and ask what you must do.",
    ),

    # ══ WEEK 4 - A2: out in the world ════════════════════════════════════════
    _lesson(
        "sk-i16", 4, 1, "A2", "Cestovanie - travel and transport",
        "buy a ticket, talk about transport; autobusom, s kamarátom (7. pád)",
        words=[
            ("vlak", "train", "qatar"),
            ("autobus", "bus", "avtobus"),
            ("električka", "tram", "tramvay"),
            ("lístok", "ticket", "bilet"),
            ("nástupište", "platform", "platforma"),
            ("odchod / príchod", "departure / arrival", "yola düşmə / gəliş"),
            ("meškať", "to be late", "gecikmək"),
            ("spiatočný", "return (ticket)", "gediş-qayıdış"),
        ],
        phrases=[
            ("Jeden lístok do Košíc, prosím.", "One ticket to Košice, please.", "Košiceyə bir bilet, zəhmət olmasa."),
            ("Kedy ide vlak?", "When does the train go?", "Qatar nə vaxt gedir?"),
            ("Z ktorého nástupišťa?", "From which platform?", "Hansı platformadan?"),
            ("Do práce chodím električkou.", "I go to work by tram.", "İşə tramvayla gedirəm."),
            ("Vlak mešká.", "The train is late.", "Qatar gecikir."),
        ],
        grammar={
            "name": "Čím? S kým? autobusom, s kamarátom (7. pád)",
            "rule": ("Čím cestuješ? a S kým? - 7. pád: vlak → vlakom, autobus → autobusom, "
                     "električka → električkou. Kamarát → s kamarátom, sestra → so sestrou."),
            "table": ["on: vlakom, autobusom, s kamarátom", "ona: električkou, so sestrou"],
            "examples": [("Cestujem vlakom.", "I travel by train."),
                         ("Do práce chodím autobusom.", "I go to work by bus."),
                         ("Idem na výlet s kamarátom.", "I am going on a trip with a friend.")],
        },
        skills=["sk_instrumental", "sk_motion"],
        partner_role="ticket seller",
        dialogue=[
            ("learner", "Dobrý deň. Jeden lístok do Košíc, prosím.", "Good day. One ticket to Košice, please."),
            ("partner", "Jednosmerný alebo spiatočný?", "One-way or return?"),
            ("learner", "Spiatočný, prosím. Kedy ide vlak?", "Return, please. When does the train go?"),
            ("partner", "O desiatej pätnásť.", "At a quarter past ten."),
            ("learner", "Z ktorého nástupišťa?", "From which platform?"),
            ("partner", "Z tretieho nástupišťa. Šťastnú cestu!", "From platform three. Have a good trip!"),
        ],
        translate=[
            ("One ticket to Košice, please.", "Jeden lístok do Košíc, prosím."),
            ("When does the train go?", "Kedy ide vlak?"),
            ("I go to work by bus.", "Do práce chodím autobusom."),
            ("I travel with a friend.", "Cestujem s kamarátom."),
        ],
        questions=[
            ("Ako chodíš do práce?", "How do you go to work?", "Do práce chodím električkou."),
            ("S kým rád cestuješ?", "Who do you like travelling with?", "Rád cestujem s rodinou."),
        ],
        speak="Role play at the station: buy a ticket, ask the time and platform. Then say how you travel every day.",
    ),
    _lesson(
        "sk-i17", 4, 2, "A2", "Môj názor - my opinion",
        "give your opinion and reasons; myslím, že ... / pretože",
        words=[
            ("názor", "opinion", "fikir"),
            ("myslieť", "to think", "düşünmək"),
            ("súhlasiť", "to agree", "razılaşmaq"),
            ("zaujímavý", "interesting", "maraqlı"),
            ("ťažký / ľahký", "difficult / easy", "çətin / asan"),
            ("dôležitý", "important", "vacib"),
            ("pretože", "because", "çünki"),
            ("podľa mňa", "in my opinion", "məncə"),
        ],
        phrases=[
            ("Myslím, že je to dobrý nápad.", "I think it is a good idea.", "Məncə bu yaxşı fikirdir."),
            ("Súhlasím.", "I agree.", "Razıyam."),
            ("Nesúhlasím, pretože ...", "I don't agree because ...", "Razı deyiləm, çünki ..."),
            ("Podľa mňa je slovenčina ťažká.", "In my opinion Slovak is difficult.", "Məncə slovak dili çətindir."),
            ("To je pravda.", "That is true.", "Bu doğrudur."),
        ],
        grammar={
            "name": "že a pretože - dlhšie vety",
            "rule": ("Myslím, že ... = I think that ... Pretože / lebo = because. Pred 'že' a 'pretože' "
                     "je vždy čiarka. Tak robíš z dvoch krátkych viet jednu dlhšiu."),
            "table": ["Myslím, že + veta", "veta, pretože + veta"],
            "examples": [("Myslím, že Bratislava je pekná.", "I think Bratislava is beautiful."),
                         ("Učím sa po slovensky, pretože tu bývam.", "I learn Slovak because I live here."),
                         ("Myslím, že mám pravdu.", "I think I am right.")],
        },
        skills=["sk_ze_aby"],
        partner_role="colleague",
        dialogue=[
            ("partner", "Je podľa teba slovenčina ťažká?", "Do you think Slovak is difficult?"),
            ("learner", "Áno, myslím, že je ťažká, ale zaujímavá.", "Yes, I think it is difficult but interesting."),
            ("partner", "Prečo sa ju učíš?", "Why are you learning it?"),
            ("learner", "Pretože tu bývam a pracujem.", "Because I live and work here."),
            ("partner", "Myslím, že hovoríš už dobre!", "I think you already speak well!"),
            ("learner", "Ďakujem, ale musím sa ešte veľa učiť.", "Thank you, but I still have to learn a lot."),
        ],
        translate=[
            ("I think it is a good idea.", "Myslím, že je to dobrý nápad."),
            ("I agree.", "Súhlasím."),
            ("I learn Slovak because I live here.", "Učím sa po slovensky, pretože tu bývam."),
            ("In my opinion it is important.", "Podľa mňa je to dôležité."),
        ],
        questions=[
            ("Je slovenčina ťažká? Prečo?", "Is Slovak difficult? Why?", "Myslím, že je ťažká, pretože má veľa koncoviek."),
            ("Páči sa ti tvoja práca? Prečo?", "Do you like your job? Why?", "Áno, pretože je zaujímavá."),
        ],
        speak="Give your opinion on three things (Bratislava, your job, learning Slovak) with a reason for each.",
    ),
    _lesson(
        "sk-i18", 4, 3, "A2", "Porovnávanie - comparing",
        "compare things; väčší, lepší, najlepší",
        words=[
            ("veľký / väčší", "big / bigger", "böyük / daha böyük"),
            ("malý / menší", "small / smaller", "kiçik / daha kiçik"),
            ("dobrý / lepší", "good / better", "yaxşı / daha yaxşı"),
            ("zlý / horší", "bad / worse", "pis / daha pis"),
            ("drahší / lacnejší", "more expensive / cheaper", "daha baha / daha ucuz"),
            ("rýchly / rýchlejší", "fast / faster", "sürətli / daha sürətli"),
            ("teplý / studený", "warm / cold", "isti / soyuq"),
            ("ako", "than, like", "-dan, kimi"),
        ],
        phrases=[
            ("Baku je väčšie ako Bratislava.", "Baku is bigger than Bratislava.", "Bakı Bratislavadan böyükdür."),
            ("Vlak je rýchlejší ako autobus.", "The train is faster than the bus.", "Qatar avtobusdan sürətlidir."),
            ("Tu je to lacnejšie.", "It is cheaper here.", "Burada daha ucuzdur."),
            ("To je najlepšia reštaurácia.", "That is the best restaurant.", "Bu ən yaxşı restorandır."),
            ("V lete je v Baku teplejšie.", "In summer Baku is warmer.", "Yayda Bakıda daha istidir."),
        ],
        grammar={
            "name": "Stupňovanie - väčší, najväčší",
            "rule": ("Porovnanie: -ší alebo -ejší + ako: lacný → lacnejší ako. Najviac: naj- + -ší: najlacnejší. "
                     "Nepravidelné: dobrý → lepší, zlý → horší, veľký → väčší, malý → menší."),
            "table": ["lacný → lacnejší → najlacnejší", "dobrý → lepší → najlepší",
                      "veľký → väčší → najväčší"],
            "examples": [("Bratislava je menšia ako Baku.", "Bratislava is smaller than Baku."),
                         ("Káva je tu lacnejšia.", "Coffee is cheaper here."),
                         ("Toto je najlepší deň.", "This is the best day.")],
        },
        skills=["sk_comparatives"],
        partner_role="friend",
        dialogue=[
            ("partner", "Čo je väčšie, Baku alebo Bratislava?", "Which is bigger, Baku or Bratislava?"),
            ("learner", "Baku je oveľa väčšie ako Bratislava.", "Baku is much bigger than Bratislava."),
            ("partner", "A kde je lepšie počasie?", "And where is the weather better?"),
            ("learner", "V lete je v Baku teplejšie, ale v Bratislave je viac zelene.",
             "In summer Baku is warmer, but in Bratislava there is more green."),
            ("partner", "A kde je život drahší?", "And where is life more expensive?"),
            ("learner", "Myslím, že v Bratislave je život drahší.", "I think life is more expensive in Bratislava."),
        ],
        translate=[
            ("Baku is bigger than Bratislava.", "Baku je väčšie ako Bratislava."),
            ("The train is faster than the bus.", "Vlak je rýchlejší ako autobus."),
            ("It is cheaper here.", "Tu je to lacnejšie."),
            ("This is the best restaurant.", "Toto je najlepšia reštaurácia."),
        ],
        questions=[
            ("Čo je lepšie - vlak alebo autobus? Prečo?", "Which is better - train or bus? Why?",
             "Vlak je lepší, pretože je rýchlejší."),
            ("Kde je lacnejšie - v Baku alebo v Bratislave?", "Where is it cheaper - in Baku or Bratislava?",
             "V Baku je lacnejšie."),
        ],
        speak="Compare Baku and Bratislava: size, weather, prices, food, people.",
    ),
    _lesson(
        "sk-i19", 4, 4, "A2", "Telefonovanie - phone calls and requests",
        "make a phone call and polite requests; mohli by ste, chcel by som",
        words=[
            ("telefonovať", "to phone", "zəng etmək"),
            ("zavolať", "to call", "zəng vurmaq"),
            ("termín", "appointment, date", "görüş vaxtı"),
            ("objednať sa", "to make an appointment", "növbə almaq"),
            ("zopakovať", "to repeat", "təkrarlamaq"),
            ("pomalšie", "more slowly", "daha yavaş"),
            ("správa", "message", "mesaj"),
            ("piatok / pondelok", "Friday / Monday", "cümə / bazar ertəsi"),
        ],
        phrases=[
            ("Dobrý deň, tu je Taleh Rzayev.", "Good day, this is Taleh Rzayev.", "Salam, mən Taleh Rzayevəm."),
            ("Chcel by som sa objednať.", "I would like to make an appointment.", "Növbə almaq istərdim."),
            ("Mohli by ste to zopakovať?", "Could you repeat that?", "Təkrar edə bilərsiniz?"),
            ("Hovorte pomalšie, prosím.", "Speak more slowly, please.", "Daha yavaş danışın, zəhmət olmasa."),
            ("Hodí sa vám piatok?", "Does Friday suit you?", "Cümə sizə uyğundur?"),
        ],
        grammar={
            "name": "Zdvorilá prosba - chcel by som, mohli by ste",
            "rule": ("Zdvorilo: chcel by som (I would like) - žena: chcela by som. "
                     "Mohli by ste ...? (Could you ...?) + sloveso na -ť. Zavolám vám / ti = I'll call you."),
            "table": ["chcel by som + -ť / vec", "mohli by ste + -ť?", "zavolám ti (friend) · zavolám vám (polite)"],
            "examples": [("Chcel by som kávu.", "I would like a coffee."),
                         ("Mohli by ste mi pomôcť?", "Could you help me?"),
                         ("Zavolám vám v pondelok.", "I will call you on Monday.")],
        },
        skills=["sk_conditional", "sk_pronoun_cases"],
        partner_role="receptionist at a clinic",
        dialogue=[
            ("partner", "Ambulancia, dobrý deň.", "Clinic, good day."),
            ("learner", "Dobrý deň, tu je Taleh Rzayev. Chcel by som sa objednať.",
             "Good day, this is Taleh Rzayev. I would like to make an appointment."),
            ("partner", "Hodí sa vám piatok o deviatej?", "Does Friday at nine suit you?"),
            ("learner", "Prepáčte, mohli by ste to zopakovať pomalšie?", "Sorry, could you repeat that more slowly?"),
            ("partner", "Piatok. O deviatej hodine.", "Friday. At nine o'clock."),
            ("learner", "Áno, piatok sa mi hodí. Ďakujem, dovidenia.", "Yes, Friday suits me. Thank you, goodbye."),
        ],
        translate=[
            ("I would like to make an appointment.", "Chcel by som sa objednať."),
            ("Could you repeat that?", "Mohli by ste to zopakovať?"),
            ("Speak more slowly, please.", "Hovorte pomalšie, prosím."),
            ("I will call you on Monday.", "Zavolám vám v pondelok."),
        ],
        questions=[
            ("Komu často voláš?", "Who do you often call?", "Často volám mame."),
            ("Čo by si chcel robiť v lete?", "What would you like to do in summer?", "Chcel by som cestovať."),
        ],
        speak="Role play: phone a clinic and make an appointment. Ask them to repeat and speak slowly.",
    ),
    _lesson(
        "sk-i20", 4, 5, "A2", "Kontrolná lekcia A2 - talk about yourself",
        "talk freely for several minutes about yourself, past, present and future",
        words=[
            ("minulosť", "the past", "keçmiş"),
            ("budúcnosť", "the future", "gələcək"),
            ("sen", "dream", "arzu, yuxu"),
            ("cieľ", "goal", "məqsəd"),
            ("skúsenosť", "experience", "təcrübə"),
            ("zmeniť", "to change", "dəyişmək"),
            ("zlepšiť sa", "to improve", "yaxşılaşmaq"),
            ("plynule", "fluently", "səlis"),
        ],
        phrases=[
            ("Pred rokom som prišiel na Slovensko.", "A year ago I came to Slovakia.", "Bir il əvvəl Slovakiyaya gəldim."),
            ("Mojím cieľom je hovoriť plynule.", "My goal is to speak fluently.", "Məqsədim səlis danışmaqdır."),
            ("Za mesiac som sa veľa naučil.", "In a month I learned a lot.", "Bir ayda çox şey öyrəndim."),
            ("Chcel by som sa ešte zlepšiť.", "I would like to improve more.", "Daha da yaxşılaşmaq istərdim."),
            ("Nabudúce budem hovoriť lepšie.", "Next time I will speak better.", "Növbəti dəfə daha yaxşı danışacağam."),
        ],
        grammar={
            "name": "Všetky časy spolu - bol som, som, budem",
            "rule": ("Minulosť: robil som. Prítomnosť: robím. Budúcnosť: budem robiť. "
                     "Dobrý rozprávač spája časy slovami: predtým (before), teraz (now), v budúcnosti (in the future)."),
            "table": ["predtým: býval som v Baku", "teraz: bývam v Bratislave", "v budúcnosti: budem hovoriť plynule"],
            "examples": [("Predtým som býval v Baku.", "Before, I lived in Baku."),
                         ("Teraz bývam a pracujem v Bratislave.", "Now I live and work in Bratislava."),
                         ("V budúcnosti budem hovoriť plynule.", "In the future I will speak fluently.")],
        },
        skills=["sk_past", "sk_future", "sk_present"],
        partner_role="examiner",
        dialogue=[
            ("partner", "Povedzte mi niečo o sebe.", "Tell me something about yourself."),
            ("learner", "Volám sa Taleh, som z Azerbajdžanu a pracujem ako programátor.",
             "My name is Taleh, I am from Azerbaijan and I work as a programmer."),
            ("partner", "Prečo ste prišli na Slovensko?", "Why did you come to Slovakia?"),
            ("learner", "Prišiel som sem kvôli práci.", "I came here because of work."),
            ("partner", "Aké máte plány?", "What are your plans?"),
            ("learner", "Chcel by som tu zostať a hovoriť plynule po slovensky.",
             "I would like to stay here and speak Slovak fluently."),
        ],
        translate=[
            ("Before, I lived in Baku.", "Predtým som býval v Baku."),
            ("Now I work in Bratislava.", "Teraz pracujem v Bratislave."),
            ("My goal is to speak fluently.", "Mojím cieľom je hovoriť plynule."),
            ("In a month I learned a lot.", "Za mesiac som sa veľa naučil."),
        ],
        questions=[
            ("Povedz mi niečo o sebe.", "Tell me about yourself.", "Volám sa Taleh, som z Baku a bývam v Bratislave."),
            ("Čo si robil minulý víkend?", "What did you do last weekend?", "Minulý víkend som bol na výlete."),
            ("Aké máš plány na budúcnosť?", "What are your plans for the future?", "Chcel by som hovoriť plynule."),
        ],
        speak=("Final test: talk for 3 minutes about your past, present and future. The tutor only asks "
               "follow-up questions, then gives feedback: two strong points and two things to practise."),
    ),
]

LESSONS += [
    # ══ WEEK 5 - B1: experiences, wishes, people ═════════════════════════════
    _lesson(
        "sk-i21", 5, 1, "B1", "Moje zážitky - experiences",
        "talk about experiences (have you ever...?); robiť / urobiť (aspect)",
        words=[
            ("zážitok", "experience, adventure", "təəssürat, macəra"),
            ("v zahraničí", "abroad", "xaricdə"),
            ("už", "already, ever", "artıq, heç"),
            ("ešte nikdy", "never (yet)", "hələ heç vaxt"),
            ("niekedy", "ever, sometimes", "nə vaxtsa, bəzən"),
            ("vyskúšať", "to try", "sınamaq"),
            ("prvýkrát", "for the first time", "ilk dəfə"),
            ("zažiť", "to experience", "yaşamaq, görmək"),
        ],
        phrases=[
            ("Bol si už niekedy v Tatrách?", "Have you ever been to the Tatras?", "Heç Tatra dağlarında olmusan?"),
            ("Ešte nikdy som nebol v Prahe.", "I have never been to Prague.", "Hələ heç vaxt Praqada olmamışam."),
            ("Už som to vyskúšal.", "I have already tried it.", "Artıq bunu sınamışam."),
            ("Prvýkrát som to jedol tu.", "I ate it here for the first time.", "Onu ilk dəfə burada yedim."),
            ("Bol to skvelý zážitok.", "It was a great experience.", "Əla təcrübə idi."),
        ],
        grammar={
            "name": "Vid: robiť / urobiť",
            "rule": ("Nedokonavé sloveso (robiť, čítať) je proces alebo opakovanie. Dokonavé sloveso "
                     "(urobiť, prečítať) je jeden hotový výsledok. Otázka 'Už si to urobil?' pýta výsledok."),
            "table": ["proces: čítal som celý večer", "výsledok: prečítal som celú knihu",
                      "robiť → urobiť · čítať → prečítať · jesť → zjesť"],
            "examples": [("Celý večer som čítal knihu.", "I was reading a book all evening."),
                         ("Včera som prečítal celú knihu.", "Yesterday I read the whole book."),
                         ("Už si to urobil?", "Have you done it yet?")],
        },
        skills=["sk_aspect", "sk_past"],
        partner_role="colleague",
        dialogue=[
            ("partner", "Bol si už niekedy v Tatrách?", "Have you ever been to the Tatras?"),
            ("learner", "Áno, bol som tam minulé leto.", "Yes, I was there last summer."),
            ("partner", "A vyskúšal si bryndzové halušky?", "And did you try bryndzové halušky?"),
            ("learner", "Áno, prvýkrát som ich jedol práve v Tatrách.", "Yes, I ate them for the first time in the Tatras."),
            ("partner", "Chutili ti?", "Did you like them?"),
            ("learner", "Veľmi! Bol to skvelý zážitok.", "Very much! It was a great experience."),
        ],
        translate=[
            ("I have never been to Prague.", "Ešte nikdy som nebol v Prahe."),
            ("Have you ever tried it?", "Už si to niekedy vyskúšal?"),
            ("Yesterday I read the whole book.", "Včera som prečítal celú knihu."),
            ("It was a great experience.", "Bol to skvelý zážitok."),
        ],
        questions=[
            ("Bol si už niekedy v zahraničí? Kde?", "Have you ever been abroad? Where?",
             "Áno, bol som v Turecku a v Nemecku."),
            ("Čo si na Slovensku vyskúšal prvýkrát?", "What did you try for the first time in Slovakia?",
             "Prvýkrát som vyskúšal bryndzové halušky."),
        ],
        speak="Tell about three experiences: your best trip, something new you tried, something you have never done but want to.",
    ),
    _lesson(
        "sk-i22", 5, 2, "B1", "Keby... - wishes and dreams",
        "talk about wishes and unreal situations; keby som ..., by som ...",
        words=[
            ("keby", "if (not real)", "əgər (xəyal)"),
            ("vyhrať", "to win", "qazanmaq"),
            ("peniaze", "money", "pul"),
            ("svet", "world", "dünya"),
            ("more", "sea", "dəniz"),
            ("pomôcť", "to help", "kömək etmək"),
            ("splniť si sen", "to make a dream come true", "arzusunu həyata keçirmək"),
            ("na tvojom mieste", "if I were you", "sənin yerində"),
        ],
        phrases=[
            ("Čo by si robil, keby si vyhral milión?", "What would you do if you won a million?",
             "Bir milyon qazansaydın nə edərdin?"),
            ("Keby som mal viac času, učil by som sa každý deň.", "If I had more time, I would study every day.",
             "Daha çox vaxtım olsaydı, hər gün oxuyardım."),
            ("Kúpil by som dom pri mori.", "I would buy a house by the sea.", "Dəniz kənarında ev alardım."),
            ("Na tvojom mieste by som to skúsil.", "If I were you, I would try it.", "Sənin yerində olsaydım, sınayardım."),
            ("To by bolo super.", "That would be great.", "Bu əla olardı."),
        ],
        grammar={
            "name": "Podmieňovací spôsob: keby som ..., by som ...",
            "rule": ("Pre situáciu, ktorá nie je skutočná: tvar na -l + by: robil by som. "
                     "Podmienka: keby som + -l. Keby som mal peniaze, cestoval by som."),
            "table": ["ja: robil by som · ty: robil by si", "on: robil by · my: robili by sme",
                      "keby som mal ..., kúpil by som ..."],
            "examples": [("Keby som mal čas, išiel by som do kina.", "If I had time, I would go to the cinema."),
                         ("Čo by si robil na mojom mieste?", "What would you do in my place?"),
                         ("Rád by som ti pomohol.", "I would like to help you.")],
        },
        skills=["sk_conditional"],
        partner_role="friend",
        dialogue=[
            ("partner", "Čo by si robil, keby si vyhral milión eur?", "What would you do if you won a million euros?"),
            ("learner", "Najprv by som pomohol rodine.", "First I would help my family."),
            ("partner", "A potom?", "And then?"),
            ("learner", "Potom by som cestoval po svete.", "Then I would travel around the world."),
            ("partner", "Kúpil by si si aj dom?", "Would you also buy a house?"),
            ("learner", "Áno, keby som mohol, kúpil by som dom pri mori.", "Yes, if I could, I would buy a house by the sea."),
        ],
        translate=[
            ("If I had time, I would go to the cinema.", "Keby som mal čas, išiel by som do kina."),
            ("What would you do?", "Čo by si robil?"),
            ("I would help my family.", "Pomohol by som rodine."),
            ("That would be great.", "To by bolo super."),
        ],
        questions=[
            ("Čo by si robil, keby si vyhral milión?", "What would you do if you won a million?",
             "Keby som vyhral milión, cestoval by som po svete."),
            ("Kde by si chcel bývať, keby si mohol?", "Where would you like to live if you could?",
             "Keby som mohol, býval by som pri mori."),
        ],
        speak="Talk about your dreams with keby: a lot of money, a lot of time, living in another country.",
    ),
    _lesson(
        "sk-i23", 5, 3, "B1", "Rady - giving advice",
        "give advice and instructions; imperative and mal by si",
        words=[
            ("rada", "advice", "məsləhət"),
            ("poradiť", "to advise", "məsləhət vermək"),
            ("stres", "stress", "stres"),
            ("zdravý", "healthy", "sağlam"),
            ("spánok", "sleep", "yuxu"),
            ("pohyb", "exercise, movement", "hərəkət, idman"),
            ("pravidelne", "regularly", "müntəzəm"),
            ("prestávka", "break", "fasilə"),
        ],
        phrases=[
            ("Mal by si viac spať.", "You should sleep more.", "Daha çox yatmalısan."),
            ("Čo mi poradíš?", "What do you advise me?", "Mənə nə məsləhət görürsən?"),
            ("Skús to znova.", "Try it again.", "Yenə sına."),
            ("Nerob si starosti.", "Don't worry.", "Narahat olma."),
            ("Nezabudni si zobrať dáždnik.", "Don't forget to take an umbrella.", "Çətir götürməyi unutma."),
        ],
        grammar={
            "name": "Rozkaz a rada: rob! / mal by si",
            "rule": ("Rozkaz: rob! (ty), robte! (vy), robme! (my). Zápor: nerob! "
                     "Mäkšia rada: mal by si + -ť (you should): Mal by si viac odpočívať."),
            "table": ["ty: poď · rob · nezabudni", "vy: poďte · robte · nezabudnite",
                      "rada: mal by si / mali by ste + -ť"],
            "examples": [("Poď so mnou!", "Come with me!"),
                         ("Nezabudni zavolať mame.", "Don't forget to call mum."),
                         ("Mal by si viac odpočívať.", "You should rest more.")],
        },
        skills=["sk_imperative", "sk_conditional"],
        partner_role="tired friend",
        dialogue=[
            ("partner", "Som stále unavený. Čo mi poradíš?", "I am always tired. What do you advise me?"),
            ("learner", "Mal by si chodiť skôr spať.", "You should go to bed earlier."),
            ("partner", "Ale mám veľa práce.", "But I have a lot of work."),
            ("learner", "Tak si rob prestávky a pravidelne športuj.", "Then take breaks and do sport regularly."),
            ("partner", "Dobre, skúsim to.", "OK, I will try it."),
            ("learner", "A nerob si starosti, bude to lepšie.", "And don't worry, it will get better."),
        ],
        translate=[
            ("You should sleep more.", "Mal by si viac spať."),
            ("Don't worry.", "Nerob si starosti."),
            ("Come with me!", "Poď so mnou!"),
            ("What do you advise me?", "Čo mi poradíš?"),
        ],
        questions=[
            ("Čo by si poradil človeku, ktorý sa učí po slovensky?", "What would you advise someone learning Slovak?",
             "Mal by sa učiť každý deň a veľa hovoriť."),
            ("Čo robíš, keď máš stres?", "What do you do when you are stressed?", "Keď mám stres, idem sa prejsť."),
        ],
        speak="Give advice to three people: a tired colleague, a new student in Slovakia, a friend who wants to be healthy.",
    ),
    _lesson(
        "sk-i24", 5, 4, "B1", "Ľudia okolo mňa - describing people",
        "describe appearance and character; ktorý / ktorá / ktoré",
        words=[
            ("vysoký / nízky", "tall / short", "hündür / alçaq"),
            ("vlasy", "hair", "saç"),
            ("oči", "eyes", "gözlər"),
            ("milý", "nice, kind", "mehriban"),
            ("vtipný", "funny", "zarafatcıl"),
            ("spoľahlivý", "reliable", "etibarlı"),
            ("pokojný", "calm", "sakit"),
            ("povaha", "character", "xasiyyət"),
        ],
        phrases=[
            ("Ako vyzerá?", "What does he / she look like?", "Necə görünür?"),
            ("Má krátke čierne vlasy.", "He has short black hair.", "Qısa qara saçları var."),
            ("Je to človek, ktorý vždy pomôže.", "He is a person who always helps.", "Həmişə kömək edən bir insandır."),
            ("Je veľmi milá a vtipná.", "She is very kind and funny.", "Çox mehriban və zarafatcıldır."),
            ("Poznáš toho muža, ktorý tam stojí?", "Do you know the man standing there?", "Orada dayanan kişini tanıyırsan?"),
        ],
        grammar={
            "name": "Vzťažné vety: ktorý, ktorá, ktoré",
            "rule": ("'Ktorý' spája dve vety. Má rod slova pred ním: muž, ktorý ...; žena, ktorá ...; "
                     "dieťa, ktoré ... Keď je predmetom, mení tvar: kniha, ktorú čítam."),
            "table": ["muž, ktorý tu býva", "žena, ktorá tu pracuje", "kniha, ktorú čítam (4. pád)"],
            "examples": [("Mám kamaráta, ktorý býva v Košiciach.", "I have a friend who lives in Košice."),
                         ("To je žena, ktorá u nás pracuje.", "That is the woman who works with us."),
                         ("Kniha, ktorú čítam, je zaujímavá.", "The book I am reading is interesting.")],
        },
        skills=["sk_relative"],
        partner_role="colleague",
        dialogue=[
            ("partner", "Poznáš nového kolegu?", "Do you know the new colleague?"),
            ("learner", "Myslíš toho vysokého muža, ktorý sedí pri okne?", "You mean the tall man who sits by the window?"),
            ("partner", "Áno. Aký je?", "Yes. What is he like?"),
            ("learner", "Je veľmi milý a vtipný.", "He is very nice and funny."),
            ("partner", "A odkiaľ je?", "And where is he from?"),
            ("learner", "Je z Nitry. Je to človek, ktorý vždy pomôže.", "He is from Nitra. He is a person who always helps."),
        ],
        translate=[
            ("He has short black hair.", "Má krátke čierne vlasy."),
            ("I have a friend who lives in Košice.", "Mám kamaráta, ktorý býva v Košiciach."),
            ("She is very kind and funny.", "Je veľmi milá a vtipná."),
            ("The book I am reading is interesting.", "Kniha, ktorú čítam, je zaujímavá."),
        ],
        questions=[
            ("Opíš svojho najlepšieho kamaráta.", "Describe your best friend.",
             "Môj najlepší kamarát je vysoký a je to človek, ktorý vždy pomôže."),
            ("Aký človek si ty?", "What kind of person are you?", "Som pokojný a spoľahlivý."),
        ],
        speak="Describe three people you know: how they look and what they are like, using ktorý / ktorá.",
    ),
    _lesson(
        "sk-i25", 5, 5, "B1", "Pracovný pohovor - job interview",
        "talk about your work experience; verbs with a fixed preposition",
        words=[
            ("pohovor", "interview", "müsahibə"),
            ("životopis", "CV", "tərcümeyi-hal"),
            ("skúsenosti", "experience (work)", "təcrübə"),
            ("zodpovednosť", "responsibility", "məsuliyyət"),
            ("plat", "salary", "maaş"),
            ("tím", "team", "komanda"),
            ("zamestnávateľ", "employer", "işəgötürən"),
            ("samostatne", "independently", "müstəqil"),
        ],
        phrases=[
            ("Povedzte nám niečo o sebe.", "Tell us something about yourself.", "Özünüz haqqında danışın."),
            ("Mám päť rokov skúseností.", "I have five years of experience.", "Beş illik təcrübəm var."),
            ("Zaujímam sa o nové technológie.", "I am interested in new technologies.", "Yeni texnologiyalarla maraqlanıram."),
            ("Rád pracujem v tíme.", "I like working in a team.", "Komandada işləməyi sevirəm."),
            ("Aký je plat?", "What is the salary?", "Maaş nə qədərdir?"),
        ],
        grammar={
            "name": "Slovesá s predložkou",
            "rule": ("Niektoré slovesá majú stálu predložku a pád - uč sa ich spolu: zaujímať sa o + 4. pád "
                     "(o prácu), pracovať na + 6. pád (na projekte), tešiť sa na + 4. pád (na víkend)."),
            "table": ["zaujímať sa o + 4. pád: o technológie", "pracovať na + 6. pád: na projekte",
                      "tešiť sa na · starať sa o · čakať na"],
            "examples": [("Zaujímam sa o umelú inteligenciu.", "I am interested in artificial intelligence."),
                         ("Pracujem na novom projekte.", "I am working on a new project."),
                         ("Teším sa na víkend.", "I am looking forward to the weekend.")],
        },
        skills=["sk_verb_cases"],
        partner_role="interviewer",
        dialogue=[
            ("partner", "Dobrý deň. Povedzte nám niečo o sebe.", "Good day. Tell us something about yourself."),
            ("learner", "Volám sa Taleh, som programátor a mám päť rokov skúseností.",
             "My name is Taleh, I am a programmer and I have five years of experience."),
            ("partner", "Prečo chcete pracovať u nás?", "Why do you want to work for us?"),
            ("learner", "Zaujímam sa o nové technológie a vaša firma v tom patrí k najlepším.",
             "I am interested in new technologies and your company is among the best at it."),
            ("partner", "Radi pracujete v tíme?", "Do you like working in a team?"),
            ("learner", "Áno, rád pracujem v tíme, ale viem pracovať aj samostatne.",
             "Yes, I like working in a team, but I can also work independently."),
        ],
        translate=[
            ("I have five years of experience.", "Mám päť rokov skúseností."),
            ("I am interested in new technologies.", "Zaujímam sa o nové technológie."),
            ("I am working on a new project.", "Pracujem na novom projekte."),
            ("I am looking forward to the weekend.", "Teším sa na víkend."),
        ],
        questions=[
            ("Na čom teraz pracuješ?", "What are you working on now?", "Teraz pracujem na novej aplikácii."),
            ("O čo sa zaujímaš?", "What are you interested in?", "Zaujímam sa o technológie a šport."),
        ],
        speak="Role play a job interview: talk about yourself, your experience, why you want the job, and ask about the salary.",
    ),

    # ══ WEEK 6 - B1: real life in Slovakia ═══════════════════════════════════
    _lesson(
        "sk-i26", 6, 1, "B1", "Reklamácia - a complaint",
        "complain about a broken product; verbs with prefixes",
        words=[
            ("reklamácia", "complaint (about a product)", "şikayət, geri qaytarma"),
            ("pokaziť sa", "to break down", "xarab olmaq"),
            ("opraviť", "to repair", "təmir etmək"),
            ("vrátiť", "to return, give back", "qaytarmaq"),
            ("vymeniť", "to exchange", "dəyişdirmək"),
            ("záruka", "warranty", "zəmanət"),
            ("bloček", "receipt", "qəbz, çek"),
            ("nefunguje", "it does not work", "işləmir"),
        ],
        phrases=[
            ("Chcel by som reklamovať tento telefón.", "I would like to return this phone (it is faulty).",
             "Bu telefonu geri qaytarmaq istərdim."),
            ("Pokazil sa po týždni.", "It broke after a week.", "Bir həftədən sonra xarab oldu."),
            ("Nefunguje nabíjanie.", "The charging does not work.", "Enerji yığmır."),
            ("Môžete mi ho vymeniť?", "Can you exchange it for me?", "Onu dəyişdirə bilərsiniz?"),
            ("Mám ešte záruku.", "I still have a warranty.", "Hələ zəmanətim var."),
        ],
        grammar={
            "name": "Predpony slovies",
            "rule": ("Predpona mení význam slovesa: ísť → prísť (sem), odísť (preč), vyjsť (von), prejsť (cez). "
                     "Často robí z procesu hotový výsledok: kaziť → pokaziť, meniť → vymeniť."),
            "table": ["pri- sem · od- preč · vy- von · pre- cez", "kaziť → pokaziť · meniť → vymeniť"],
            "examples": [("Prišiel som reklamovať telefón.", "I came to return a phone."),
                         ("Telefón sa pokazil.", "The phone broke down."),
                         ("Odišiel som bez telefónu.", "I left without the phone.")],
        },
        skills=["sk_prefixes"],
        partner_role="shop assistant",
        dialogue=[
            ("learner", "Dobrý deň, chcel by som reklamovať tento telefón.", "Good day, I would like to return this phone."),
            ("partner", "Čo sa stalo?", "What happened?"),
            ("learner", "Pokazil sa po týždni. Nefunguje nabíjanie.", "It broke after a week. The charging does not work."),
            ("partner", "Máte bloček?", "Do you have the receipt?"),
            ("learner", "Áno, tu je. Mám ešte záruku.", "Yes, here it is. I still have a warranty."),
            ("partner", "Dobre, vymeníme vám ho za nový.", "OK, we will exchange it for a new one."),
        ],
        translate=[
            ("My phone broke down.", "Pokazil sa mi telefón."),
            ("It does not work.", "Nefunguje to."),
            ("Can you exchange it?", "Môžete mi ho vymeniť?"),
            ("I still have a warranty.", "Mám ešte záruku."),
        ],
        questions=[
            ("Pokazilo sa ti niekedy niečo nové?", "Has something new ever broken on you?",
             "Áno, raz sa mi pokazil nový notebook."),
            ("Čo robíš, keď niečo nefunguje?", "What do you do when something does not work?",
             "Keď niečo nefunguje, idem to reklamovať."),
        ],
        speak="Role play: return a broken product. Explain what happened and ask for an exchange or your money back.",
    ),
    _lesson(
        "sk-i27", 6, 2, "B1", "Správy - news and events",
        "talk about news and what happened; sa instead of a person (hovorí sa)",
        words=[
            ("správy", "the news", "xəbərlər"),
            ("udalosť", "event", "hadisə"),
            ("stať sa", "to happen", "baş vermək"),
            ("nehoda", "accident", "qəza"),
            ("ceny", "prices", "qiymətlər"),
            ("rásť", "to grow, to rise", "artmaq"),
            ("vraj", "reportedly, they say", "deyilənə görə"),
            ("zraniť sa", "to get hurt", "yaralanmaq"),
        ],
        phrases=[
            ("Počul si, čo sa stalo?", "Did you hear what happened?", "Nə baş verdiyini eşitdin?"),
            ("V správach hovorili, že ...", "On the news they said that ...", "Xəbərlərdə dedilər ki, ..."),
            ("Ceny stále rastú.", "Prices keep rising.", "Qiymətlər artmaqda davam edir."),
            ("Vraj bude zajtra pršať.", "They say it will rain tomorrow.", "Deyilənə görə sabah yağış yağacaq."),
            ("To je hrozné.", "That is terrible.", "Bu dəhşətdir."),
        ],
        grammar={
            "name": "sa namiesto osoby: hovorí sa, stavia sa",
            "rule": ("Keď nie je dôležité, kto to robí: sa + sloveso v 3. osobe. "
                     "Na Slovensku sa hovorí po slovensky. V meste sa stavia nová nemocnica."),
            "table": ["hovorí sa · predáva sa · stavia sa", "Ako sa to povie po slovensky?"],
            "examples": [("Na Slovensku sa hovorí po slovensky.", "In Slovakia people speak Slovak."),
                         ("V meste sa stavia nová nemocnica.", "A new hospital is being built in the city."),
                         ("Ako sa to povie po slovensky?", "How do you say it in Slovak?")],
        },
        skills=["sk_se_passive"],
        partner_role="colleague",
        dialogue=[
            ("partner", "Počul si, čo sa stalo?", "Did you hear what happened?"),
            ("learner", "Nie, čo sa stalo?", "No, what happened?"),
            ("partner", "Na diaľnici bola veľká nehoda.", "There was a big accident on the motorway."),
            ("learner", "To je hrozné. Zranil sa niekto?", "That is terrible. Did anyone get hurt?"),
            ("partner", "Vraj nikto vážne.", "Reportedly nobody seriously."),
            ("learner", "To je dobre. V správach hovorili aj to, že ceny benzínu rastú.",
             "That is good. On the news they also said that petrol prices are rising."),
        ],
        translate=[
            ("Did you hear what happened?", "Počul si, čo sa stalo?"),
            ("Prices keep rising.", "Ceny stále rastú."),
            ("A new hospital is being built in the city.", "V meste sa stavia nová nemocnica."),
            ("How do you say it in Slovak?", "Ako sa to povie po slovensky?"),
        ],
        questions=[
            ("Čo nové sa stalo tento týždeň?", "What new happened this week?",
             "Tento týždeň sa v meste otvorila nová reštaurácia."),
            ("Aké správy čítaš?", "What news do you read?", "Čítam správy o technológiách."),
        ],
        speak="Tell the tutor two pieces of news (from your country, your city or your work) and give your opinion on them.",
    ),
    _lesson(
        "sk-i28", 6, 3, "B1", "Na úrade - at the office",
        "sort things out at an office; plural in cases (s dokladmi)",
        words=[
            ("úrad", "office (authority)", "idarə"),
            ("povolenie na pobyt", "residence permit", "yaşayış icazəsi"),
            ("tlačivo", "form", "blank, anket"),
            ("doklad / doklady", "document(s)", "sənəd(lər)"),
            ("pas", "passport", "pasport"),
            ("poplatok", "fee", "rüsum"),
            ("vybaviť", "to sort out, arrange", "həll etmək, düzəltmək"),
            ("podpis", "signature", "imza"),
        ],
        phrases=[
            ("Potrebujem si predĺžiť povolenie na pobyt.", "I need to extend my residence permit.",
             "Yaşayış icazəmi uzatmalıyam."),
            ("Aké doklady potrebujem?", "What documents do I need?", "Hansı sənədlər lazımdır?"),
            ("Kde môžem vyplniť tlačivo?", "Where can I fill in the form?", "Blankı harada doldura bilərəm?"),
            ("Koľko je poplatok?", "How much is the fee?", "Rüsum nə qədərdir?"),
            ("Ako dlho to bude trvať?", "How long will it take?", "Nə qədər çəkəcək?"),
        ],
        grammar={
            "name": "Množné číslo v pádoch",
            "rule": ("Aj v množnom čísle sa menia koncovky: doklady → s dokladmi (7. pád), bez dokladov "
                     "(2. pád), úrady → na úradoch (6. pád). Ľudia → s ľuďmi."),
            "table": ["s + 7. pád: s dokladmi, s kolegami", "bez + 2. pád: bez dokladov",
                      "na / v + 6. pád: na úradoch, v mestách"],
            "examples": [("Prišiel som s dokladmi.", "I came with the documents."),
                         ("Bez dokladov to nevybavíte.", "Without documents you can't sort it out."),
                         ("Na úradoch je vždy veľa ľudí.", "There are always many people at the offices.")],
        },
        skills=["sk_plural_cases", "sk_genitive"],
        partner_role="clerk at the foreign police",
        dialogue=[
            ("partner", "Dobrý deň, čo potrebujete?", "Good day, what do you need?"),
            ("learner", "Dobrý deň, potrebujem si predĺžiť povolenie na pobyt.", "Good day, I need to extend my residence permit."),
            ("partner", "Máte všetky doklady?", "Do you have all the documents?"),
            ("learner", "Mám pas, pracovnú zmluvu a fotky. Potrebujem ešte niečo?",
             "I have my passport, work contract and photos. Do I need anything else?"),
            ("partner", "Áno, vyplňte toto tlačivo a zaplaťte poplatok.", "Yes, fill in this form and pay the fee."),
            ("learner", "Dobre. Ako dlho to bude trvať?", "OK. How long will it take?"),
        ],
        translate=[
            ("What documents do I need?", "Aké doklady potrebujem?"),
            ("I came with the documents.", "Prišiel som s dokladmi."),
            ("How much is the fee?", "Koľko je poplatok?"),
            ("How long will it take?", "Ako dlho to bude trvať?"),
        ],
        questions=[
            ("Čo si už musel vybaviť na úrade?", "What have you had to sort out at an office?",
             "Musel som si vybaviť povolenie na pobyt."),
            ("Čo je podľa teba na úradoch najťažšie?", "What do you think is the hardest thing at offices?",
             "Najťažšie sú dlhé rady a veľa dokladov."),
        ],
        speak="Role play at the foreign police: extend your residence permit, ask what you need, the fee and how long it takes.",
    ),
    _lesson(
        "sk-i29", 6, 4, "B1", "Sviatky a tradície - holidays and traditions",
        "compare traditions; že (fact) and aby (purpose, wish)",
        words=[
            ("tradícia", "tradition", "ənənə"),
            ("sviatok", "holiday, feast", "bayram"),
            ("Vianoce", "Christmas", "Milad"),
            ("Veľká noc", "Easter", "Pasxa"),
            ("oslavovať", "to celebrate", "qeyd etmək"),
            ("zvyk", "custom", "adət"),
            ("darček", "present, gift", "hədiyyə"),
            ("sladkosti", "sweets", "şirniyyat"),
        ],
        phrases=[
            ("Ako oslavujete Vianoce?", "How do you celebrate Christmas?", "Miladı necə qeyd edirsiniz?"),
            ("U nás sa oslavuje Novruz.", "In our country Novruz is celebrated.", "Bizdə Novruz qeyd olunur."),
            ("Je zvykom, že sa stretne celá rodina.", "It is a custom that the whole family meets.",
             "Adətdir ki, bütün ailə bir yerə yığışır."),
            ("Chcem, aby si to vyskúšal.", "I want you to try it.", "İstəyirəm ki, bunu sınayasan."),
            ("Dávame si darčeky.", "We give each other presents.", "Bir-birimizə hədiyyə veririk."),
        ],
        grammar={
            "name": "že a aby",
            "rule": ("'Že' hovorí fakt: Viem, že prídeš. 'Aby' hovorí cieľ alebo želanie, a po ňom je tvar na -l: "
                     "Chcem, aby si prišiel. Varíme, aby sme oslávili sviatok."),
            "table": ["fakt: Myslím, že ...", "želanie: Chcem, aby si + -l", "cieľ: ..., aby sme + -l"],
            "examples": [("Myslím, že Novruz je krásny sviatok.", "I think Novruz is a beautiful holiday."),
                         ("Chcem, aby si prišiel k nám na Novruz.", "I want you to come to us for Novruz."),
                         ("Mama varí plov, aby sme oslávili sviatok.", "Mum cooks plov so that we celebrate the holiday.")],
        },
        skills=["sk_ze_aby"],
        partner_role="Slovak friend",
        dialogue=[
            ("partner", "Aký je najväčší sviatok v Azerbajdžane?", "What is the biggest holiday in Azerbaijan?"),
            ("learner", "Najväčší sviatok je Novruz. Oslavuje sa na jar.", "The biggest holiday is Novruz. It is celebrated in spring."),
            ("partner", "A ako ho oslavujete?", "And how do you celebrate it?"),
            ("learner", "Je zvykom, že sa stretne celá rodina a pečieme sladkosti.",
             "It is a custom that the whole family meets and we bake sweets."),
            ("partner", "To znie krásne.", "That sounds beautiful."),
            ("learner", "Chcem, aby si to raz zažil s nami.", "I want you to experience it with us one day."),
        ],
        translate=[
            ("How do you celebrate Christmas?", "Ako oslavujete Vianoce?"),
            ("I think it is a beautiful holiday.", "Myslím, že je to krásny sviatok."),
            ("I want you to come to us.", "Chcem, aby si prišiel k nám."),
            ("We give each other presents.", "Dávame si darčeky."),
        ],
        questions=[
            ("Aký je tvoj obľúbený sviatok? Prečo?", "What is your favourite holiday? Why?",
             "Môj obľúbený sviatok je Novruz, pretože je to začiatok jari."),
            ("Ktorú slovenskú tradíciu poznáš?", "Which Slovak tradition do you know?",
             "Poznám Vianoce a kapustnicu."),
        ],
        speak="Compare a holiday in Azerbaijan and in Slovakia: when, how people celebrate, food and customs. Use že and aby.",
    ),
    _lesson(
        "sk-i30", 6, 5, "B1", "Záverečná B1 skúška - final B1 test",
        "argue for and against, tell a story and talk about plans fluently",
        words=[
            ("výhoda / nevýhoda", "advantage / disadvantage", "üstünlük / çatışmazlıq"),
            ("na jednej strane", "on the one hand", "bir tərəfdən"),
            ("na druhej strane", "on the other hand", "digər tərəfdən"),
            ("navyše", "moreover", "üstəlik"),
            ("preto", "that is why", "ona görə"),
            ("však", "however", "lakin"),
            ("celkovo", "overall", "ümumilikdə"),
            ("presvedčiť", "to convince", "inandırmaq"),
        ],
        phrases=[
            ("Na jednej strane ..., na druhej strane ...", "On the one hand ..., on the other hand ...",
             "Bir tərəfdən ..., digər tərəfdən ..."),
            ("Navyše je to lacnejšie.", "Moreover, it is cheaper.", "Üstəlik, daha ucuzdur."),
            ("Preto si myslím, že ...", "That is why I think that ...", "Ona görə düşünürəm ki, ..."),
            ("Celkovo som spokojný.", "Overall I am satisfied.", "Ümumilikdə razıyam."),
            ("Súhlasím s tebou len čiastočne.", "I only partly agree with you.", "Səninlə qismən razıyam."),
        ],
        grammar={
            "name": "Spájacie výrazy na argument",
            "rule": ("Na dobrý argument: na jednej strane / na druhej strane (dve strany), navyše (a ešte), "
                     "však (ale), preto (výsledok), celkovo (všetko spolu)."),
            "table": ["na jednej strane ... na druhej strane ...", "navyše · však · preto · celkovo"],
            "examples": [("Na jednej strane je Bratislava malá, na druhej strane je pokojná.",
                          "On the one hand Bratislava is small, on the other hand it is calm."),
                         ("Navyše je tu dobrá práca.", "Moreover, there is good work here."),
                         ("Preto tu chcem zostať.", "That is why I want to stay here.")],
        },
        skills=["sk_discourse", "sk_conditional", "sk_past"],
        partner_role="examiner",
        dialogue=[
            ("partner", "Je lepšie bývať v meste alebo na dedine?", "Is it better to live in a city or a village?"),
            ("learner", "Na jednej strane je mesto pohodlné, lebo je tam všetko blízko.",
             "On the one hand the city is comfortable because everything is near."),
            ("partner", "A na druhej strane?", "And on the other hand?"),
            ("learner", "Na druhej strane je tam hluk a byty sú drahé.", "On the other hand it is noisy and flats are expensive."),
            ("partner", "Takže čo by ste si vybrali?", "So what would you choose?"),
            ("learner", "Celkovo by som radšej býval v meste, pretože tam mám prácu.",
             "Overall I would rather live in the city because I have work there."),
        ],
        translate=[
            ("Moreover, it is cheaper.", "Navyše je to lacnejšie."),
            ("That is why I want to stay here.", "Preto tu chcem zostať."),
            ("Overall I am satisfied.", "Celkovo som spokojný."),
            ("I only partly agree with you.", "Súhlasím s tebou len čiastočne."),
        ],
        questions=[
            ("Je lepšie pracovať z domu alebo v kancelárii? Prečo?", "Is it better to work from home or in an office? Why?",
             "Na jednej strane je práca z domu pohodlná, na druhej strane mi chýbajú kolegovia."),
            ("Ako sa zmenil tvoj život na Slovensku?", "How has your life changed in Slovakia?",
             "Predtým som býval v Baku, teraz bývam v Bratislave a hovorím po slovensky."),
        ],
        speak=("Final B1 test, about 5 minutes: argue a topic with pros and cons, tell a story from the past and "
               "talk about your plans with keby. The tutor only asks follow-up questions, then gives feedback: "
               "two strong points and two things to practise."),
    ),
]

COURSE = {
    "id": "slovak_intensive",
    "language": "slovak",
    "title": "Slovak · A1 → B1 · 6 weeks",
    "weeks": [
        {"week": 1, "title": "Me and my world", "band": "A1"},
        {"week": 2, "title": "Every day", "band": "A1"},
        {"week": 3, "title": "Past and future", "band": "A2"},
        {"week": 4, "title": "Out in the world", "band": "A2"},
        {"week": 5, "title": "Experiences, wishes, people", "band": "B1"},
        {"week": 6, "title": "Real life in Slovakia", "band": "B1"},
    ],
    "lessons": LESSONS,
}
